In [1]:
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait 
from selenium.webdriver.support import expected_conditions
from bs4 import BeautifulSoup
import re
import pandas as pd
import numpy as np
from selenium.common.exceptions import StaleElementReferenceException

In [ ]:
##Extracting the data from MAKE MY TRIP('www.makemytrip.com')

In [2]:
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=AMD-DEL-27/10/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635268619363&forwardFlowRequired=true&mpo=&intl=false'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
##First grabbing the url to access the web, using the webdriver

name1=soup.find_all('span',class_='boldFont blackText airlineName') ### getting the names of the Airlines
Airlines1=[]
for i in name1:
    Airlines1.append(i.get_text())
    
print(len(Airlines1))  

dep_time1=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter') ### getting the departure and arrival times of the Airlines
dep1, arr1 =dep_time1[::2], dep_time1[1::2]##Splitting the list into two as it was getting both the imformation together
DEP1=[]
for i in dep1:
    DEP1.append(i.get_text())
    ARV1=[]
for i in arr1:
    ARV1.append( i.get_text())
print(len(DEP1),len(ARV1))

layover1=soup.find_all('p',class_='flightsLayoverInfo')### getting the layover taken by the Airlines.
Lay_over1=[]
for l in layover1:
    Lay_over1.append(l.get_text())

dep_place1=soup.find_all('p', class_='darkText')### getting the departure and arrival plces of the Airlines
dep_place1, arr_place1 =dep_place1[::2], dep_place1[1::2]##Splitting the list into two as it was getting both the imformation together
origin1=[]
for i in dep_place1:
    origin1.append(i.get_text())
    destination1=[]
for i in arr_place1:
    destination1.append(i.get_text())
print(len(origin1),len(destination1))

price1=[]
pri1=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')### getting the price of the Airlines
for i in pri1:
    price1.append(i.get_text())
    print(len(price1))


try:    
    dur1=driver.find_elements_by_xpath('//div[@class="stop-info flexOne"]/p')### getting the duration of the Airlines
    Dur1=[]
    for i in dur1:
        Dur1.append(i.text)
        print(len(Dur1))
except StaleElementReferenceException as e:
    print("Exception raised", e)

23
23 23
23 23
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23

##### creating the dataset.
-- later these will be concatinated together.

In [3]:
df1=pd.DataFrame()
df1['Airline_name']= Airlines1[0:23]
df1['Departure']=DEP1[0:23]
df1['Arrival']=ARV1[0:23]
df1['Source']=origin1[0:23]
df1['Destination']=destination1[0:23]
df1['Lay_over']=Lay_over1[0:23]
df1['Price']=price1[0:23]
df1['Duration']=Dur1[0:23]
df1

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,Go First,09:10,10:45,Ahmedabad,New Delhi,Non stop,"₹ 5,060",01 h 35 m
1,Go First,13:25,15:00,Ahmedabad,New Delhi,Non stop,"₹ 5,060",01 h 35 m
2,Go First,17:30,19:05,Ahmedabad,New Delhi,Non stop,"₹ 5,060",01 h 35 m
3,Spicejet,06:10,11:10,Ahmedabad,New Delhi,1 stop via Jaipur,"₹ 5,060",05 h
4,Spicejet,06:10,11:10,Ahmedabad,New Delhi,1 stop via Jaipur,"₹ 5,060",
5,Go First,08:45,17:50,Ahmedabad,New Delhi,1 stop via Mumbai,"₹ 5,060",
6,Go First,06:40,17:50,Ahmedabad,New Delhi,1 stop via Kolkata,"₹ 5,060",
7,Go First,10:00,19:55,Ahmedabad,New Delhi,1 stop via Goa,"₹ 5,060",
8,Go First,09:00,23:55,Ahmedabad,New Delhi,1 stop via Bengaluru,"₹ 5,060",
9,Go First,19:55,00:20,Ahmedabad,New Delhi,1 stop via Mumbai,"₹ 5,060",
10,Go First,21:35,08:05,Ahmedabad,New Delhi,1 stop via Mumbai,"₹ 5,060",
11,IndiGo,09:30,11:10,Ahmedabad,New Delhi,Non stop,"₹ 5,061",01 h 40 m
12,IndiGo,11:05,13:00,Ahmedabad,New Delhi,Non stop,"₹ 5,061",01 h 55 m
13,IndiGo,17:35,19:15,Ahmedabad,New Delhi,Non stop,"₹ 5,061",01 h 40 m
14,IndiGo,10:40,18:20,Ahmedabad,New Delhi,1 stop via Chandigarh,"₹ 5,061",07 h 40 m
15,Air India,12:30,14:45,Ahmedabad,New Delhi,Non stop,"₹ 5,062",02 h 15 m
16,Air India,22:20,23:55,Ahmedabad,New Delhi,Non stop,"₹ 5,062",01 h 35 m
17,Vistara,10:55,12:35,Ahmedabad,New Delhi,Non stop,"₹ 5,167",01 h 40 m
18,Vistara,08:40,10:25,Ahmedabad,New Delhi,Non stop,"₹ 5,377",01 h 45 m
19,Spicejet,18:15,11:10,Ahmedabad,New Delhi,1 stop via Jaipur,"₹ 5,480",16 h 55 m
20,IndiGo,08:30,15:15,Ahmedabad,New Delhi,1 stop via Lucknow,"₹ 5,518",06 h 45 m
21,IndiGo,06:15,07:50,Ahmedabad,New Delhi,Non stop,"₹ 5,639",01 h 35 m
22,IndiGo,20:45,22:15,Ahmedabad,New Delhi,Non stop,"₹ 5,901",01 h 30 m

In [5]:
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-AMD-27/10/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635269097609&forwardFlowRequired=true&mpo='
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')


name2=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines2=[]
for i in name2:
    Airlines2.append(i.get_text())
    
print(len(Airlines2))  

dep_time2=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep2, arr2 =dep_time2[::2], dep_time2[1::2]
DEP2=[]
for i in dep2:
    DEP2.append(i.get_text())
    ARV2=[]
for i in arr2:
    ARV2.append( i.get_text())
print(len(DEP2),len(ARV2))

layover2=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over2=[]
for l in layover2:
    Lay_over2.append(l.get_text())

dep_place2=soup.find_all('p', class_='darkText')
dep_place2, arr_place2 =dep_place2[::2], dep_place2[1::2]
origin2=[]
for i in dep_place2:
    origin2.append(i.get_text())
    destination2=[]
for i in arr_place2:
    destination2.append(i.get_text())
print(len(origin2),len(destination2))

price2=[]
pri2=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri2:
    price2.append(i.get_text())
    print(len(price2))


try:    
    dur2=driver.find_elements_by_xpath('//div[@class="stop-info flexOne"]/p')
    Dur2=[]
    for i in dur2:
        Dur2.append(i.text)
        print(len(Dur2))
except StaleElementReferenceException as e:
    print("Exception raised", e)

23
23 23
23 23
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23

In [6]:
df2=pd.DataFrame()
df2['Airline_name']= Airlines2[0:23]
df2['Departure']=DEP2[0:23]
df2['Arrival']=ARV2[0:23]
df2['Source']=origin2[0:23]
df2['Destination']=destination2[0:23]
df2['Lay_over']=Lay_over2[0:23]
df2['Price']=price2[0:23]
df2['Duration']=Dur2[0:23]
df2

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,Go First,07:10,08:35,New Delhi,Ahmedabad,Non stop,"₹ 5,114",01 h 25 m
1,Go First,15:30,17:00,New Delhi,Ahmedabad,Non stop,"₹ 5,114",01 h 30 m
2,Go First,19:40,21:05,New Delhi,Ahmedabad,Non stop,"₹ 5,114",01 h 25 m
3,Spicejet,20:10,21:50,New Delhi,Ahmedabad,Non stop,"₹ 5,114",01 h 40 m
4,Spicejet,05:55,11:20,New Delhi,Ahmedabad,1 stop via Jaipur,"₹ 5,114",05 h 25 m
5,Spicejet,05:55,11:20,New Delhi,Ahmedabad,1 stop via Jaipur,"₹ 5,114",
6,Go First,06:15,12:55,New Delhi,Ahmedabad,1 stop via Mumbai,"₹ 5,114",
7,Go First,10:40,17:10,New Delhi,Ahmedabad,1 stop via Goa,"₹ 5,114",
8,Go First,08:10,17:10,New Delhi,Ahmedabad,1 stop via Goa,"₹ 5,114",
9,Go First,05:45,19:25,New Delhi,Ahmedabad,1 stop via Kolkata,"₹ 5,114",
10,Go First,14:20,21:05,New Delhi,Ahmedabad,1 stop via Mumbai,"₹ 5,114",
11,Go First,09:20,21:05,New Delhi,Ahmedabad,1 stop via Mumbai,"₹ 5,114",
12,Go First,22:45,08:10,New Delhi,Ahmedabad,1 stop via Mumbai,"₹ 5,114",
13,Go First,20:30,08:10,New Delhi,Ahmedabad,1 stop via Mumbai,"₹ 5,114",
14,Go First,19:45,08:30,New Delhi,Ahmedabad,1 stop via Bengaluru,"₹ 5,114",
15,Air India,06:20,08:35,New Delhi,Ahmedabad,Non stop,"₹ 5,115",02 h 15 m
16,Vistara,06:30,08:05,New Delhi,Ahmedabad,Non stop,"₹ 5,115",01 h 35 m
17,IndiGo,07:20,09:00,New Delhi,Ahmedabad,Non stop,"₹ 5,115",01 h 40 m
18,IndiGo,08:55,10:35,New Delhi,Ahmedabad,Non stop,"₹ 5,115",01 h 40 m
19,IndiGo,13:50,15:15,New Delhi,Ahmedabad,Non stop,"₹ 5,115",01 h 25 m
20,Vistara,18:00,19:40,New Delhi,Ahmedabad,Non stop,"₹ 5,115",01 h 40 m
21,IndiGo,18:45,20:15,New Delhi,Ahmedabad,Non stop,"₹ 5,115",01 h 30 m
22,Air India,20:10,21:30,New Delhi,Ahmedabad,Non stop,"₹ 5,115",01 h 20 m

In [7]:
df2.to_csv('flight_price02.csv',index='False')

In [8]:
df1.to_csv('flight_price01.csv',index='False')

In [12]:
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-UDR-27/10/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635269608171&forwardFlowRequired=true&mpo=&intl=false'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')


name3=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines3=[]
for i in name3:
    Airlines3.append(i.get_text())
    
print(len(Airlines3))  

dep_time3=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep3, arr3 =dep_time3[::2], dep_time3[1::2]
DEP3=[]
for i in dep3:
    DEP3.append(i.get_text())
    ARV3=[]
for i in arr3:
    ARV3.append( i.get_text())
print(len(DEP3),len(ARV3))

layover3=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over3=[]
for l in layover3:
    Lay_over3.append(l.get_text())

dep_place3=soup.find_all('p', class_='darkText')
dep_place3, arr_place3 =dep_place3[::2], dep_place3[1::2]
origin3=[]
for i in dep_place3:
    origin3.append(i.get_text())
    destination3=[]
for i in arr_place3:
    destination3.append(i.get_text())
print(len(origin3),len(destination3))

price3=[]
pri3=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri3:
    price3.append(i.get_text())
    print(len(price3))


try:    
    dur3=driver.find_elements_by_xpath('//div[@class="stop-info flexOne"]/p')
    Dur3=[]
    for i in dur3:
        Dur3.append(i.text)
        print(len(Dur3))
except StaleElementReferenceException as e:
    print("Exception raised", e)

19
19 19
19 19
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19

In [13]:
df3=pd.DataFrame()
df3['Airline_name']= Airlines3[0:23]
df3['Departure']=DEP3[0:23]
df3['Arrival']=ARV3[0:23]
df3['Source']=origin3[0:23]
df3['Destination']=destination3[0:23]
df3['Lay_over']=Lay_over3[0:23]
df3['Price']=price3[0:23]
df3['Duration']=Dur3[0:23]
df3

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,IndiGo,16:25,17:45,New Delhi,Udaipur,Non stop,"₹ 4,275",01 h 20 m
1,Spicejet,18:30,19:50,New Delhi,Udaipur,Non stop,"₹ 4,275",01 h 20 m
2,Spicejet,05:55,08:30,New Delhi,Udaipur,1 stop via Jaipur,"₹ 4,275",02 h 35 m
3,Spicejet,20:10,08:15,New Delhi,Udaipur,1 stop via Ahmedabad,"₹ 4,275",12 h 05 m
4,Vistara,13:20,14:45,New Delhi,Udaipur,Non stop,"₹ 4,328",01 h 25 m
5,IndiGo,07:40,09:00,New Delhi,Udaipur,Non stop,"₹ 5,535",01 h 20 m
6,Vistara,06:00,13:45,New Delhi,Udaipur,1 stop via Mumbai,"₹ 9,840",07 h 45 m
7,Vistara,06:00,13:45,New Delhi,Udaipur,1 stop via Mumbai,"₹ 9,840",
8,Vistara,18:55,13:45,New Delhi,Udaipur,1 stop via Mumbai,"₹ 10,260",
9,Vistara,17:45,13:45,New Delhi,Udaipur,1 stop via Mumbai,"₹ 10,260",
10,Vistara,15:10,13:45,New Delhi,Udaipur,1 stop via Mumbai,"₹ 10,260",
11,Vistara,19:45,13:45,New Delhi,Udaipur,1 stop via Mumbai,"₹ 10,365",
12,Vistara,08:50,13:45,New Delhi,Udaipur,1 stop via Mumbai,"₹ 10,890",
13,Vistara,21:40,13:45,New Delhi,Udaipur,1 stop via Mumbai,"₹ 11,310",
14,Vistara,16:55,13:45,New Delhi,Udaipur,1 stop via Mumbai,"₹ 11,310",
15,Air India,20:00,15:40,New Delhi,Udaipur,"2 stop via Bhopal,Mumbai","₹ 12,613",
16,Air India,10:40,15:40,New Delhi,Udaipur,1 stop via Mumbai,"₹ 12,675",
17,Air India,21:25,15:40,New Delhi,Udaipur,"2 stop via Hyderabad,Mumbai","₹ 14,670",
18,Air India,17:40,15:40,New Delhi,Udaipur,"3 stop via Ranchi,Hyderabad,Mumbai","₹ 14,670",

In [14]:
df3.to_csv('flight_price03.csv',index='False')

In [16]:
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-JDH-27/10/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635270221685&forwardFlowRequired=true&mpo=&intl=false'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')


name4=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines4=[]
for i in name4:
    Airlines4.append(i.get_text())
    
print(len(Airlines4))  

dep_time4=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep4, arr4 =dep_time4[::2], dep_time4[1::2]
DEP4=[]
for i in dep4:
    DEP4.append(i.get_text())
    ARV4=[]
for i in arr4:
    ARV4.append( i.get_text())
print(len(DEP4),len(ARV4))

layover4=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over4=[]
for l in layover4:
    Lay_over4.append(l.get_text())

dep_place4=soup.find_all('p', class_='darkText')
dep_place4, arr_place4 =dep_place4[::2], dep_place4[1::2]
origin4=[]
for i in dep_place4:
    origin4.append(i.get_text())
    destination4=[]
for i in arr_place4:
    destination4.append(i.get_text())
print(len(origin4),len(destination4))

price4=[]
pri4=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri4:
    price4.append(i.get_text())
    print(len(price4))


try:    
    dur4=driver.find_elements_by_xpath('//div[@class="stop-info flexOne"]/p')
    Dur4=[]
    for i in dur4:
        Dur4.append(i.text)
        print(len(Dur4))
except StaleElementReferenceException as e:
    print("Exception raised", e)

17
17 17
17 17
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17

In [17]:
df4=pd.DataFrame()
df4['Airline_name']= Airlines4[0:23]
df4['Departure']=DEP4[0:23]
df4['Arrival']=ARV4[0:23]
df4['Source']=origin4[0:23]
df4['Destination']=destination4[0:23]
df4['Lay_over']=Lay_over4[0:23]
df4['Price']=price4[0:23]
df4['Duration']=Dur4[0:23]
df4

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,IndiGo,09:35,10:55,New Delhi,Jodhpur,Non stop,"₹ 5,115",01 h 20 m
1,IndiGo,13:10,14:30,New Delhi,Jodhpur,Non stop,"₹ 5,115",01 h 20 m
2,Air India,12:30,15:00,New Delhi,Jodhpur,1 stop via Jaipur,"₹ 5,115",02 h 30 m
3,Vistara,06:00,14:55,New Delhi,Jodhpur,1 stop via Mumbai,"₹ 10,680",08 h 55 m
4,Vistara,18:55,14:55,New Delhi,Jodhpur,1 stop via Mumbai,"₹ 10,680",20 h
5,Vistara,17:45,14:55,New Delhi,Jodhpur,1 stop via Mumbai,"₹ 10,680",21 h 10 m
6,Vistara,10:20,14:55,New Delhi,Jodhpur,1 stop via Mumbai,"₹ 10,785",04 h 35 m
7,Vistara,19:45,14:55,New Delhi,Jodhpur,1 stop via Mumbai,"₹ 10,785",19 h 10 m
8,"Go First, Air India",06:15,12:15,New Delhi,Jodhpur,1 stop via Mumbai,"₹ 11,057",06 h
9,"Go First, Vistara",09:20,14:55,New Delhi,Jodhpur,1 stop via Mumbai,"₹ 11,057",05 h 35 m
10,"Vistara, Air India",06:00,12:15,New Delhi,Jodhpur,1 stop via Mumbai,"₹ 11,058",06 h 15 m
11,"Spicejet, Vistara",06:50,14:55,New Delhi,Jodhpur,1 stop via Mumbai,"₹ 11,058",08 h 05 m
12,"IndiGo, Air India",06:10,12:15,New Delhi,Jodhpur,1 stop via Mumbai,"₹ 11,268",06 h 05 m
13,"IndiGo, Vistara",08:55,14:55,New Delhi,Jodhpur,1 stop via Mumbai,"₹ 11,268",06 h
14,"Spicejet, IndiGo",06:50,12:45,New Delhi,Jodhpur,1 stop via Mumbai,"₹ 11,373",05 h 55 m
15,Vistara,09:30,14:55,New Delhi,Jodhpur,1 stop via Mumbai,"₹ 11,730",05 h 25 m
16,Vistara,08:50,14:55,New Delhi,Jodhpur,1 stop via Mumbai,"₹ 11,730",06 h 05 m

In [18]:
df4.to_csv('flight_price04.csv',index='False')

In [2]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-BLR-02/11/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635270969935&forwardFlowRequired=true&mpo='
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')


name5=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines5=[]
for i in name5:
    Airlines5.append(i.get_text())
    
print(len(Airlines5))  

dep_time5=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep5, arr5 =dep_time5[::2], dep_time5[1::2]
DEP5=[]
for i in dep5:
    DEP5.append(i.get_text())
    ARV5=[]
for i in arr5:
    ARV5.append( i.get_text())
print(len(DEP5),len(ARV5))

layover5=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over5=[]
for l in layover5:
    Lay_over5.append(l.get_text())

dep_place5=soup.find_all('p', class_='darkText')
dep_place5, arr_place5 =dep_place5[::2], dep_place5[1::2]
origin5=[]
for i in dep_place5:
    origin5.append(i.get_text())
    destination5=[]
for i in arr_place5:
    destination5.append(i.get_text())
print(len(origin5),len(destination5))

price5=[]
pri5=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri5:
    price5.append(i.get_text())
    print(len(price5))


try:    
    dur5=driver.find_elements_by_xpath('//div[@class="stop-info flexOne"]/p')
    Dur5=[]
    for i in dur5:
        Dur5.append(i.text)
        print(len(Dur5))
except StaleElementReferenceException as e:
    print("Exception raised", e)

37
37 37
38 38
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37

In [3]:
df5=pd.DataFrame()
df5['Airline_name']= Airlines5[0:37]
df5['Departure']=DEP5[0:37]
df5['Arrival']=ARV5[0:37]
df5['Source']=origin5[0:37]
df5['Destination']=destination5[0:37]
df5['Lay_over']=Lay_over5[0:37]
df5['Price']=price5[0:37]
df5['Duration']=Dur5[0:37]
df5

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,AirAsia,07:10,14:00,New Delhi,Bengaluru,1 stop via Guwahati,"₹ 7,423",06 h 50 m
1,AirAsia,07:10,14:00,New Delhi,Bengaluru,1 stop via Guwahati,"₹ 7,423",
2,AirAsia,05:45,14:00,New Delhi,Bengaluru,1 stop via Guwahati,"₹ 7,423",
3,AirAsia,04:25,14:45,New Delhi,Bengaluru,1 stop via Mumbai,"₹ 7,423",
4,AirAsia,16:05,20:40,New Delhi,Bengaluru,1 stop via Pune,"₹ 7,423",
5,AirAsia,15:25,20:40,New Delhi,Bengaluru,1 stop via Pune,"₹ 7,423",
6,AirAsia,12:40,23:10,New Delhi,Bengaluru,"2 stop via Goa,Hyderabad","₹ 7,423",
7,AirAsia,16:50,00:25,New Delhi,Bengaluru,1 stop via Kolkata,"₹ 7,423",
8,AirAsia,21:00,11:35,New Delhi,Bengaluru,1 stop via Kolkata,"₹ 7,423",
9,AirAsia,22:10,14:45,New Delhi,Bengaluru,"2 stop via Jaipur,Mumbai","₹ 7,423",
10,Go First,06:05,08:40,New Delhi,Bengaluru,Non stop,"₹ 7,424",02 h 35 m
11,Go First,18:40,21:25,New Delhi,Bengaluru,Non stop,"₹ 7,424",02 h 45 m
12,Go First,02:00,07:40,New Delhi,Bengaluru,1 stop via Mumbai,"₹ 7,424",05 h 40 m
13,Go First,02:00,07:40,New Delhi,Bengaluru,1 stop via Mumbai,"₹ 7,424",
14,Go First,05:35,10:20,New Delhi,Bengaluru,1 stop via Ranchi,"₹ 7,424",
15,Go First,05:50,12:10,New Delhi,Bengaluru,1 stop via Kolkata,"₹ 7,424",
16,Go First,09:10,13:30,New Delhi,Bengaluru,1 stop via Varanasi,"₹ 7,424",
17,Go First,10:30,16:10,New Delhi,Bengaluru,1 stop via Mumbai,"₹ 7,424",
18,Go First,09:00,16:25,New Delhi,Bengaluru,1 stop via Lucknow,"₹ 7,424",
19,Go First,12:45,19:20,New Delhi,Bengaluru,1 stop via Pune,"₹ 7,424",
20,Go First,15:00,22:45,New Delhi,Bengaluru,1 stop via Mumbai,"₹ 7,424",
21,Go First,18:05,00:35,New Delhi,Bengaluru,1 stop via Mumbai,"₹ 7,424",
22,IndiGo,02:30,05:25,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 55 m
23,IndiGo,04:15,07:10,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 55 m
24,Spicejet,05:00,07:30,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 30 m
25,Spicejet,05:35,08:05,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 30 m
26,IndiGo,06:10,08:50,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 40 m
27,Air India,06:10,08:55,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 45 m
28,IndiGo,07:20,10:15,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 55 m
29,Vistara,08:05,10:50,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 45 m
30,IndiGo,08:20,11:15,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 55 m
31,IndiGo,09:15,12:10,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 55 m
32,IndiGo,12:00,14:55,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 55 m
33,Vistara,14:15,17:05,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 50 m
34,IndiGo,15:30,18:30,New Delhi,Bengaluru,Non stop,"₹ 7,425",03 h
35,Vistara,16:05,18:50,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 45 m
36,Air India,17:20,20:05,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 45 m

In [4]:
df5.to_csv('flight_price05.csv',index='False')

In [46]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-BLR-02/11/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635270969935&forwardFlowRequired=true&mpo='
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)
driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div[2]/div/span').click()
driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()
driver.execute_script("window.scrollTo(0, 200000000);")
name6=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines6=[]
for i in name6:
    Airlines6.append(i.get_text())
    
print(len(Airlines6))  

dep_time6=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep6, arr6 =dep_time6[::2], dep_time6[1::2]
DEP6=[]
for i in dep6:
    DEP6.append(i.get_text())
    ARV6=[]
for i in arr6:
    ARV6.append( i.get_text())
print(len(DEP6),len(ARV6))

layover6=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over6=[]
for l in layover6:
    Lay_over6.append(l.get_text())

dep_place6=soup.find_all('p', class_='darkText')
dep_place6, arr_place6 =dep_place6[::2], dep_place6[1::2]
origin6=[]
for i in dep_place6:
    origin6.append(i.get_text())
    destination6=[]
for i in arr_place6:
    destination6.append(i.get_text())
print(len(origin6),len(destination6))

price6=[]
pri6=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri6:
    price6.append(i.get_text())
    print(len(price6))


try:    
    dur6=driver.find_elements_by_xpath('//div[@class="stop-info flexOne"]/p')
    Dur6=[]
    for i in dur6:
        Dur6.append(i.text)
        print(len(Dur6))
except StaleElementReferenceException as e:
    print("Exception raised", e)

37
37 37
38 38
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39

In [47]:
df6=pd.DataFrame()
df6['Airline_name']= Airlines6[0:37]
df6['Departure']=DEP6[0:37]
df6['Arrival']=ARV6[0:37]
df6['Source']=origin6[0:37]
df6['Destination']=destination6[0:37]
df6['Lay_over']=Lay_over6[0:37]
df6['Price']=price6[0:37]
df6['Duration']=Dur6[0:37]
df6

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,AirAsia,05:00,11:35,New Delhi,Bengaluru,1 stop via Kolkata,"₹ 7,423",06 h 35 m
1,AirAsia,05:00,11:35,New Delhi,Bengaluru,1 stop via Kolkata,"₹ 7,423",06 h 50 m
2,AirAsia,07:10,14:00,New Delhi,Bengaluru,1 stop via Guwahati,"₹ 7,423",08 h 15 m
3,AirAsia,05:45,14:00,New Delhi,Bengaluru,1 stop via Guwahati,"₹ 7,423",05 h 15 m
4,AirAsia,09:25,14:40,New Delhi,Bengaluru,1 stop via Ranchi,"₹ 7,423",04 h 35 m
5,AirAsia,16:05,20:40,New Delhi,Bengaluru,1 stop via Pune,"₹ 7,423",05 h 15 m
6,AirAsia,15:25,20:40,New Delhi,Bengaluru,1 stop via Pune,"₹ 7,423",05 h 50 m
7,AirAsia,15:40,21:30,New Delhi,Bengaluru,1 stop via Ranchi,"₹ 7,423",07 h 35 m
8,AirAsia,16:50,00:25,New Delhi,Bengaluru,1 stop via Kolkata,"₹ 7,423",08 h 45 m
9,AirAsia,16:15,01:00,New Delhi,Bengaluru,1 stop via Visakhapatnam,"₹ 7,423",08 h 15 m
10,AirAsia,20:00,04:15,New Delhi,Bengaluru,1 stop via Mumbai,"₹ 7,423",02 h 35 m
11,Go First,06:05,08:40,New Delhi,Bengaluru,Non stop,"₹ 7,424",02 h 45 m
12,Go First,18:40,21:25,New Delhi,Bengaluru,Non stop,"₹ 7,424",05 h 40 m
13,Go First,02:00,07:40,New Delhi,Bengaluru,1 stop via Mumbai,"₹ 7,424",04 h 45 m
14,Go First,02:00,07:40,New Delhi,Bengaluru,1 stop via Mumbai,"₹ 7,424",04 h 20 m
15,Go First,05:35,10:20,New Delhi,Bengaluru,1 stop via Ranchi,"₹ 7,424",05 h 40 m
16,Go First,09:10,13:30,New Delhi,Bengaluru,1 stop via Varanasi,"₹ 7,424",07 h 25 m
17,Go First,10:30,16:10,New Delhi,Bengaluru,1 stop via Mumbai,"₹ 7,424",06 h 35 m
18,Go First,09:00,16:25,New Delhi,Bengaluru,1 stop via Lucknow,"₹ 7,424",07 h 45 m
19,Go First,12:45,19:20,New Delhi,Bengaluru,1 stop via Pune,"₹ 7,424",06 h 30 m
20,Go First,15:00,22:45,New Delhi,Bengaluru,1 stop via Mumbai,"₹ 7,424",02 h 55 m
21,Go First,18:05,00:35,New Delhi,Bengaluru,1 stop via Mumbai,"₹ 7,424",02 h 55 m
22,IndiGo,02:30,05:25,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 30 m
23,IndiGo,04:15,07:10,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 30 m
24,Spicejet,05:00,07:30,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 40 m
25,Spicejet,05:35,08:05,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 45 m
26,IndiGo,06:10,08:50,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 45 m
27,Air India,06:10,08:55,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 55 m
28,Vistara,06:15,09:00,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 45 m
29,IndiGo,07:20,10:15,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 55 m
30,Vistara,08:05,10:50,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 55 m
31,IndiGo,08:20,11:15,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 55 m
32,IndiGo,09:15,12:10,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 50 m
33,IndiGo,12:00,14:55,New Delhi,Bengaluru,Non stop,"₹ 7,425",03 h
34,Vistara,14:15,17:05,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 45 m
35,IndiGo,15:30,18:30,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 45 m
36,Vistara,16:05,18:50,New Delhi,Bengaluru,Non stop,"₹ 7,425",02 h 50 m

In [48]:
df6.to_csv('flight_price06.csv',index='False')

In [60]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-MAA-02/11/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635275894160&forwardFlowRequired=true&mpo=&intl=false'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)
driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div[2]/div/span').click()
driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name7=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines7=[]
for i in name7:
    Airlines7.append(i.get_text())
    
print(len(Airlines7))  

dep_time7=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep7, arr7 =dep_time7[::2], dep_time7[1::2]
DEP7=[]
for i in dep7:
    DEP7.append(i.get_text())
    ARV7=[]
for i in arr7:
    ARV7.append( i.get_text())
print(len(DEP7),len(ARV7))

layover7=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over7=[]
for l in layover7:
    Lay_over7.append(l.get_text())

dep_place7=soup.find_all('p', class_='darkText')
dep_place7, arr_place7 =dep_place7[::2], dep_place7[1::2]
origin7=[]
for i in dep_place7:
    origin7.append(i.get_text())
    destination7=[]
for i in arr_place7:
    destination7.append(i.get_text())
print(len(origin7),len(destination7))

price7=[]
pri7=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri7:
    price7.append(i.get_text())
    print(len(price7))


dur7=soup.find_all('div',class_="stop-info flexOne")
Dur7=[]
for i in dur7:
    soup.find_all('p')
    Dur7.append(i.get_text())
    print(len(Dur7))

47
47 47
48 48
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47

In [61]:
df7=pd.DataFrame()
df7['Airline_name']= Airlines7[0:47]
df7['Departure']=DEP7[0:47]
df7['Arrival']=ARV7[0:47]
df7['Source']=origin7[0:47]
df7['Destination']=destination7[0:47]
df7['Lay_over']=Lay_over7[0:47]
df7['Price']=price7[0:47]
df7['Duration']=Dur7[0:47]
df7

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,Spicejet,05:45,08:25,New Delhi,Chennai,Non stop,"₹ 7,425",02 h 40 m Non stop
1,Air India,06:05,08:55,New Delhi,Chennai,Non stop,"₹ 7,425",02 h 50 m Non stop
2,Spicejet,06:15,09:10,New Delhi,Chennai,Non stop,"₹ 7,425",02 h 55 m Non stop
3,IndiGo,07:25,10:10,New Delhi,Chennai,Non stop,"₹ 7,425",02 h 45 m Non stop
4,Air India,09:45,12:40,New Delhi,Chennai,Non stop,"₹ 7,425",02 h 55 m Non stop
5,IndiGo,12:45,15:40,New Delhi,Chennai,Non stop,"₹ 7,425",02 h 55 m Non stop
6,IndiGo,17:30,20:25,New Delhi,Chennai,Non stop,"₹ 7,425",02 h 55 m Non stop
7,Spicejet,17:55,20:35,New Delhi,Chennai,Non stop,"₹ 7,425",02 h 40 m Non stop
8,Spicejet,18:25,21:10,New Delhi,Chennai,Non stop,"₹ 7,425",02 h 45 m Non stop
9,IndiGo,18:45,21:45,New Delhi,Chennai,Non stop,"₹ 7,425",03 h Non stop
10,IndiGo,20:30,23:20,New Delhi,Chennai,Non stop,"₹ 7,425",02 h 50 m Non stop
11,IndiGo,02:30,08:20,New Delhi,Chennai,1 stop via Bengaluru,"₹ 7,425",05 h 50 m 1 stop via Bengaluru
12,IndiGo,02:30,08:20,New Delhi,Chennai,1 stop via Bengaluru,"₹ 7,425",05 h 50 m 1 stop via Bengaluru
13,IndiGo,05:10,10:05,New Delhi,Chennai,1 stop via Visakhapatnam,"₹ 7,425",04 h 55 m 1 stop via Visakhapatnam
14,IndiGo,04:15,10:25,New Delhi,Chennai,1 stop via Bengaluru,"₹ 7,425",06 h 10 m 1 stop via Bengaluru
15,IndiGo,06:10,12:00,New Delhi,Chennai,1 stop via Bengaluru,"₹ 7,425",05 h 50 m 1 stop via Bengaluru
16,IndiGo,07:25,12:25,New Delhi,Chennai,1 stop via Jaipur,"₹ 7,425",05 h 1 stop via Jaipur
17,IndiGo,06:05,12:25,New Delhi,Chennai,1 stop via Jaipur,"₹ 7,425",06 h 20 m 1 stop via Jaipur
18,IndiGo,09:40,15:05,New Delhi,Chennai,1 stop via Hyderabad,"₹ 7,425",05 h 25 m 1 stop via Hyderabad
19,IndiGo,07:55,15:05,New Delhi,Chennai,1 stop via Hyderabad,"₹ 7,425",07 h 10 m 1 stop via Hyderabad
20,IndiGo,06:45,15:05,New Delhi,Chennai,1 stop via Hyderabad,"₹ 7,425",08 h 20 m 1 stop via Hyderabad
21,IndiGo,09:15,15:55,New Delhi,Chennai,1 stop via Bengaluru,"₹ 7,425",06 h 40 m 1 stop via Bengaluru
22,IndiGo,08:20,15:55,New Delhi,Chennai,1 stop via Bengaluru,"₹ 7,425",07 h 35 m 1 stop via Bengaluru
23,IndiGo,11:10,16:30,New Delhi,Chennai,1 stop via Pune,"₹ 7,425",05 h 20 m 1 stop via Pune
24,IndiGo,08:25,16:30,New Delhi,Chennai,1 stop via Pune,"₹ 7,425",08 h 05 m 1 stop via Pune
25,IndiGo,13:00,17:40,New Delhi,Chennai,1 stop via Hyderabad,"₹ 7,425",04 h 40 m 1 stop via Hyderabad
26,IndiGo,11:00,17:40,New Delhi,Chennai,1 stop via Hyderabad,"₹ 7,425",06 h 40 m 1 stop via Hyderabad
27,Spicejet,11:55,17:55,New Delhi,Chennai,1 stop via Shirdi,"₹ 7,425",06 h 1 stop via Shirdi
28,IndiGo,12:00,19:15,New Delhi,Chennai,1 stop via Bengaluru,"₹ 7,425",07 h 15 m 1 stop via Bengaluru
29,IndiGo,15:00,20:00,New Delhi,Chennai,1 stop via Lucknow,"₹ 7,425",05 h 1 stop via Lucknow
30,IndiGo,13:00,20:00,New Delhi,Chennai,1 stop via Lucknow,"₹ 7,425",07 h 1 stop via Lucknow
31,IndiGo,14:40,21:05,New Delhi,Chennai,1 stop via Raipur,"₹ 7,425",06 h 25 m 1 stop via Raipur
32,IndiGo,15:30,23:45,New Delhi,Chennai,1 stop via Bengaluru,"₹ 7,425",08 h 15 m 1 stop via Bengaluru
33,IndiGo,19:30,00:25,New Delhi,Chennai,1 stop via Hyderabad,"₹ 7,425",04 h 55 m 1 stop via Hyderabad
34,IndiGo,17:45,00:25,New Delhi,Chennai,1 stop via Hyderabad,"₹ 7,425",06 h 40 m 1 stop via Hyderabad
35,IndiGo,23:05,05:55,New Delhi,Chennai,1 stop via Hyderabad,"₹ 7,425",06 h 50 m 1 stop via Hyderabad
36,Vistara,07:20,10:10,New Delhi,Chennai,Non stop,"₹ 7,426",02 h 50 m Non stop
37,Vistara,13:30,16:20,New Delhi,Chennai,Non stop,"₹ 7,426",02 h 50 m Non stop
38,Vistara,19:55,22:45,New Delhi,Chennai,Non stop,"₹ 7,426",02 h 50 m Non stop
39,Go First,02:00,07:40,New Delhi,Chennai,1 stop via Mumbai,"₹ 7,426",05 h 40 m 1 stop via Mumbai
40,Go First,02:00,07:40,New Delhi,Chennai,1 stop via Mumbai,"₹ 7,426",05 h 40 m 1 stop via Mumbai
41,AirAsia,09:35,16:30,New Delhi,Chennai,1 stop via Bengaluru,"₹ 7,426",06 h 55 m 1 stop via Bengaluru
42,Go First,15:00,22:20,New Delhi,Chennai,1 stop via Mumbai,"₹ 7,426",07 h 20 m 1 stop via Mumbai
43,Go First,14:20,22:20,New Delhi,Chennai,1 stop via Mumbai,"₹ 7,426",08 h 1 stop via Mumbai
44,IndiGo,16:20,19:10,New Delhi,Chennai,Non stop,"₹ 7,950",02 h 50 m Non stop
45,Vistara,17:25,20:15,New Delhi,Chennai,Non stop,"₹ 8,266",02 h 50 m Non stop
46,IndiGo,14:00,19:20,New Delhi,Chennai,1 stop via Nagpur,"₹ 8,717",05 h 20 m 1 stop via Nagpur

In [62]:
df7.to_csv('flight_price07.csv',index='False')

In [4]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-GOI-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635276529414&forwardFlowRequired=true&mpo=&intl=false'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name8=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines8=[]
for i in name8:
    Airlines8.append(i.get_text())
    
print(len(Airlines8))  

dep_time8=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep8, arr8 =dep_time8[::2], dep_time8[1::2]
DEP8=[]
for i in dep8:
    DEP8.append(i.get_text())
    ARV8=[]
for i in arr8:
    ARV8.append( i.get_text())
print(len(DEP8),len(ARV8))

layover8=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over8=[]
for l in layover8:
    Lay_over8.append(l.get_text())

dep_place8=soup.find_all('p', class_='darkText')
dep_place8, arr_place8 =dep_place8[::2], dep_place8[1::2]
origin8=[]
for i in dep_place8:
    origin8.append(i.get_text())
    destination8=[]
for i in arr_place8:
    destination8.append(i.get_text())
print(len(origin8),len(destination8))

price8=[]
pri8=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri8:
    price8.append(i.get_text())
    print(len(price8))


dur8=soup.find_all('div',class_="stop-info flexOne")
Dur8=[]
for i in dur8:
    soup.find_all('p')
    Dur8.append(i.get_text())
    print(len(Dur8))

45
45 45
45 45
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45

In [21]:
dur8=soup.find_all('div',class_="stop-info flexOne")
Dur8=[]
for i in dur8:
    soup.find_all('p')
    Dur8.append(i.get_text())  
    for i in Dur8:
        n = 9
        l, r = i[::n], i[n::]

' Non stop'

In [17]:
for j in Dur8:
    for i in range(0,len(j)):
        n = 9
        split_strings=[]
        for index in range(0, len(j), n):
            split_strings.append(j[index : index + n])
        
split_strings

['02 h 30 m', ' Non stop']

In [65]:

df8=pd.DataFrame()
df8['Airline_name']= Airlines7[0:40]
df8['Departure']=DEP7[0:40]
df8['Arrival']=ARV7[0:40]
df8['Source']=origin7[0:40]
df8['Destination']=destination8[0:40]
df8['Lay_over']=Lay_over8[0:40]
df8['Price']=price8[0:40]

df8['Duration']=Dur8[0:40]
df8

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,Spicejet,05:45,08:25,New Delhi,Goa,1 stop via Mumbai,"₹ 4,321",04 h 35 m 1 stop via Mumbai
1,Air India,06:05,08:55,New Delhi,Goa,1 stop via Mumbai,"₹ 4,321",04 h 35 m 1 stop via Mumbai
2,Spicejet,06:15,09:10,New Delhi,Goa,1 stop via Mumbai,"₹ 4,360",05 h 20 m 1 stop via Mumbai
3,IndiGo,07:25,10:10,New Delhi,Goa,1 stop via Mumbai,"₹ 4,360",08 h 25 m 1 stop via Mumbai
4,Air India,09:45,12:40,New Delhi,Goa,1 stop via Mumbai,"₹ 4,360",12 h 55 m 1 stop via Mumbai
5,IndiGo,12:45,15:40,New Delhi,Goa,1 stop via Mumbai,"₹ 4,360",15 h 25 m 1 stop via Mumbai
6,IndiGo,17:30,20:25,New Delhi,Goa,1 stop via Mumbai,"₹ 4,360",07 h 40 m 1 stop via Mumbai
7,Spicejet,17:55,20:35,New Delhi,Goa,1 stop via Mumbai,"₹ 4,360",09 h 10 m 1 stop via Mumbai
8,Spicejet,18:25,21:10,New Delhi,Goa,1 stop via Mumbai,"₹ 4,360",10 h 30 m 1 stop via Mumbai
9,IndiGo,18:45,21:45,New Delhi,Goa,1 stop via Mumbai,"₹ 4,536",05 h 15 m 1 stop via Mumbai
10,IndiGo,20:30,23:20,New Delhi,Goa,1 stop via Mumbai,"₹ 4,536",06 h 05 m 1 stop via Mumbai
11,IndiGo,02:30,08:20,New Delhi,Goa,"2 stop via Indore,Mumbai","₹ 4,629","05 h 25 m 2 stop via Indore,Mumbai"
12,IndiGo,02:30,08:20,New Delhi,Goa,1 stop via Mumbai,"₹ 4,786",06 h 1 stop via Mumbai
13,IndiGo,05:10,10:05,New Delhi,Goa,1 stop via Mumbai,"₹ 4,786",09 h 30 m 1 stop via Mumbai
14,IndiGo,04:15,10:25,New Delhi,Goa,1 stop via Mumbai,"₹ 4,944",09 h 50 m 1 stop via Mumbai
15,IndiGo,06:10,12:00,New Delhi,Goa,Non stop,"₹ 4,947",02 h 35 m Non stop
16,IndiGo,07:25,12:25,New Delhi,Goa,1 stop via Mumbai,"₹ 4,992",09 h 05 m 1 stop via Mumbai
17,IndiGo,06:05,12:25,New Delhi,Goa,1 stop via Mumbai,"₹ 4,992",09 h 05 m 1 stop via Mumbai
18,IndiGo,09:40,15:05,New Delhi,Goa,1 stop via Mumbai,"₹ 5,310",04 h 45 m 1 stop via Mumbai
19,IndiGo,07:55,15:05,New Delhi,Goa,1 stop via Mumbai,"₹ 5,310",05 h 45 m 1 stop via Mumbai
20,IndiGo,06:45,15:05,New Delhi,Goa,Non stop,"₹ 5,552",02 h 30 m Non stop
21,IndiGo,09:15,15:55,New Delhi,Goa,Non stop,"₹ 5,676",02 h 35 m Non stop
22,IndiGo,08:20,15:55,New Delhi,Goa,Non stop,"₹ 5,972",02 h 40 m Non stop
23,IndiGo,11:10,16:30,New Delhi,Goa,Non stop,"₹ 6,186",02 h 30 m Non stop
24,IndiGo,08:25,16:30,New Delhi,Goa,Non stop,"₹ 6,731",02 h 35 m Non stop
25,IndiGo,13:00,17:40,New Delhi,Goa,1 stop via Hyderabad,"₹ 6,795",06 h 05 m 1 stop via Hyderabad
26,IndiGo,11:00,17:40,New Delhi,Goa,1 stop via Hyderabad,"₹ 6,795",06 h 05 m 1 stop via Hyderabad
27,Spicejet,11:55,17:55,New Delhi,Goa,1 stop via Hyderabad,"₹ 6,795",07 h 15 m 1 stop via Hyderabad
28,IndiGo,12:00,19:15,New Delhi,Goa,1 stop via Hyderabad,"₹ 6,795",07 h 50 m 1 stop via Hyderabad
29,IndiGo,15:00,20:00,New Delhi,Goa,1 stop via Hyderabad,"₹ 6,795",05 h 50 m 1 stop via Hyderabad
30,IndiGo,13:00,20:00,New Delhi,Goa,Non stop,"₹ 6,835",02 h 30 m Non stop
31,IndiGo,14:40,21:05,New Delhi,Goa,Non stop,"₹ 6,835",02 h 35 m Non stop
32,IndiGo,15:30,23:45,New Delhi,Goa,1 stop via Bengaluru,"₹ 7,088",06 h 10 m 1 stop via Bengaluru
33,IndiGo,19:30,00:25,New Delhi,Goa,1 stop via Bengaluru,"₹ 7,088",06 h 10 m 1 stop via Bengaluru
34,IndiGo,17:45,00:25,New Delhi,Goa,1 stop via Bengaluru,"₹ 7,088",07 h 40 m 1 stop via Bengaluru
35,IndiGo,23:05,05:55,New Delhi,Goa,1 stop via Ahmedabad,"₹ 7,149",04 h 40 m 1 stop via Ahmedabad
36,Vistara,07:20,10:10,New Delhi,Goa,Non stop,"₹ 7,380",02 h 45 m Non stop
37,Vistara,13:30,16:20,New Delhi,Goa,1 stop via Mumbai,"₹ 7,461",06 h 1 stop via Mumbai
38,Vistara,19:55,22:45,New Delhi,Goa,Non stop,"₹ 7,549",02 h 45 m Non stop
39,Go First,02:00,07:40,New Delhi,Goa,Non stop,"₹ 7,549",02 h 45 m Non stop

In [87]:
df8.to_csv('flight_price08.csv',index='False')

In [22]:
df=pd.read_csv('flight_price08.csv')
df

,Unnamed: 0,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,0,Air India,06:05,08:55,New Delhi,Goa,"2 stop via Indore,Mumbai","₹ 3,988","07 h 30 m 2 stop via Indore,Mumbai"
1,1,Spicejet,06:15,09:10,New Delhi,Goa,"2 stop via Indore,Mumbai","₹ 3,988","07 h 30 m 2 stop via Indore,Mumbai"
2,2,IndiGo,07:25,10:10,New Delhi,Goa,1 stop via Mumbai,"₹ 3,988",14 h 35 m 1 stop via Mumbai
3,3,IndiGo,12:45,15:40,New Delhi,Goa,1 stop via Mumbai,"₹ 4,116",05 h 20 m 1 stop via Mumbai
4,4,IndiGo,17:30,20:25,New Delhi,Goa,1 stop via Mumbai,"₹ 4,116",08 h 25 m 1 stop via Mumbai
5,5,Spicejet,18:25,21:10,New Delhi,Goa,1 stop via Mumbai,"₹ 4,116",12 h 55 m 1 stop via Mumbai
6,6,IndiGo,18:45,21:45,New Delhi,Goa,1 stop via Mumbai,"₹ 4,116",15 h 25 m 1 stop via Mumbai
7,7,IndiGo,20:30,23:20,New Delhi,Goa,1 stop via Mumbai,"₹ 4,303",11 h 55 m 1 stop via Mumbai
8,8,IndiGo,02:30,08:20,New Delhi,Goa,1 stop via Mumbai,"₹ 4,303",13 h 35 m 1 stop via Mumbai
9,9,IndiGo,02:30,08:20,New Delhi,Goa,1 stop via Mumbai,"₹ 4,303",15 h 35 m 1 stop via Mumbai
10,10,IndiGo,05:10,10:05,New Delhi,Goa,1 stop via Mumbai,"₹ 4,321",04 h 35 m 1 stop via Mumbai
11,11,IndiGo,04:15,10:25,New Delhi,Goa,1 stop via Mumbai,"₹ 4,360",07 h 40 m 1 stop via Mumbai
12,12,IndiGo,06:10,12:00,New Delhi,Goa,1 stop via Mumbai,"₹ 4,360",09 h 10 m 1 stop via Mumbai
13,13,IndiGo,07:25,12:25,New Delhi,Goa,1 stop via Mumbai,"₹ 4,360",10 h 30 m 1 stop via Mumbai
14,14,IndiGo,06:05,12:25,New Delhi,Goa,Non stop,"₹ 4,500",02 h 45 m Non stop
15,15,IndiGo,09:40,15:05,New Delhi,Goa,1 stop via Mumbai,"₹ 4,536",05 h 15 m 1 stop via Mumbai
16,16,IndiGo,07:55,15:05,New Delhi,Goa,1 stop via Mumbai,"₹ 4,536",05 h 15 m 1 stop via Mumbai
17,17,IndiGo,09:15,15:55,New Delhi,Goa,1 stop via Mumbai,"₹ 4,536",06 h 05 m 1 stop via Mumbai
18,18,IndiGo,08:20,15:55,New Delhi,Goa,"2 stop via Indore,Mumbai","₹ 4,629","05 h 25 m 2 stop via Indore,Mumbai"
19,19,IndiGo,11:10,16:30,New Delhi,Goa,1 stop via Mumbai,"₹ 4,748",09 h 05 m 1 stop via Mumbai
20,20,IndiGo,08:25,16:30,New Delhi,Goa,1 stop via Mumbai,"₹ 4,944",09 h 50 m 1 stop via Mumbai
21,21,IndiGo,13:00,17:40,New Delhi,Goa,Non stop,"₹ 4,947",02 h 35 m Non stop
22,22,IndiGo,11:00,17:40,New Delhi,Goa,Non stop,"₹ 5,256",02 h 35 m Non stop
23,23,Spicejet,11:55,17:55,New Delhi,Goa,1 stop via Mumbai,"₹ 5,310",06 h 1 stop via Mumbai
24,24,IndiGo,12:00,19:15,New Delhi,Goa,Non stop,"₹ 5,552",02 h 30 m Non stop
25,25,IndiGo,13:40,19:25,New Delhi,Goa,Non stop,"₹ 5,972",02 h 40 m Non stop
26,26,IndiGo,15:00,20:00,New Delhi,Goa,Non stop,"₹ 6,186",02 h 30 m Non stop
27,27,IndiGo,13:00,20:00,New Delhi,Goa,Non stop,"₹ 6,731",02 h 35 m Non stop
28,28,IndiGo,19:30,00:25,New Delhi,Goa,1 stop via Hyderabad,"₹ 6,795",06 h 05 m 1 stop via Hyderabad
29,29,IndiGo,17:45,00:25,New Delhi,Goa,1 stop via Hyderabad,"₹ 6,795",06 h 05 m 1 stop via Hyderabad
30,30,IndiGo,23:05,05:55,New Delhi,Goa,1 stop via Hyderabad,"₹ 6,795",07 h 15 m 1 stop via Hyderabad
31,31,Vistara,13:30,16:20,New Delhi,Goa,1 stop via Hyderabad,"₹ 6,795",07 h 50 m 1 stop via Hyderabad
32,32,Go First,02:00,07:40,New Delhi,Goa,1 stop via Hyderabad,"₹ 6,795",05 h 40 m 1 stop via Hyderabad
33,33,Go First,02:00,07:40,New Delhi,Goa,Non stop,"₹ 6,835",02 h 30 m Non stop
34,34,AirAsia,08:00,13:45,New Delhi,Goa,Non stop,"₹ 6,835",02 h 35 m Non stop
35,35,AirAsia,09:25,15:05,New Delhi,Goa,1 stop via Mumbai,"₹ 6,950",05 h 30 m 1 stop via Mumbai
36,36,AirAsia,09:35,16:30,New Delhi,Goa,1 stop via Mumbai,"₹ 6,950",06 h 30 m 1 stop via Mumbai
37,37,Go First,15:00,22:20,New Delhi,Goa,Non stop,"₹ 7,022",02 h 25 m Non stop
38,38,Go First,14:20,22:20,New Delhi,Goa,1 stop via Bengaluru,"₹ 7,088",07 h 40 m 1 stop via Bengaluru
39,39,Go First,19:55,01:10,New Delhi,Goa,1 stop via Ahmedabad,"₹ 7,149",04 h 40 m 1 stop via Ahmedabad

In [23]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-GAU-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635282457095&forwardFlowRequired=true&mpo=&intl=false'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name9=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines9=[]
for i in name9:
    Airlines9.append(i.get_text())
    
print(len(Airlines9))  

dep_time9=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep9, arr9 =dep_time9[::2], dep_time9[1::2]
DEP9=[]
for i in dep9:
    DEP9.append(i.get_text())
    ARV9=[]
for i in arr9:
    ARV9.append( i.get_text())
print(len(DEP9),len(ARV9))

layover9=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over9=[]
for l in layover9:
    Lay_over9.append(l.get_text())

dep_place9=soup.find_all('p', class_='darkText')
dep_place9, arr_place9 =dep_place9[::2], dep_place9[1::2]
origin9=[]
for i in dep_place9:
    origin9.append(i.get_text())
    destination9=[]
for i in arr_place9:
    destination9.append(i.get_text())
print(len(origin9),len(destination8))

price9=[]
pri9=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri9:
    price9.append(i.get_text())
    print(len(price9))


dur9=soup.find_all('div',class_="stop-info flexOne")
Dur9=[]
for i in dur9:
    soup.find_all('p')
    Dur9.append(i.get_text())
    print(len(Dur9))

15
15 15
15 45
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15

In [24]:

df9=pd.DataFrame()
df9['Airline_name']= Airlines9[0:30]
df9['Departure']=DEP9[0:30]
df9['Arrival']=ARV9[0:30]
df9['Source']=origin9[0:30]
df9['Destination']=destination9[0:30]
df9['Lay_over']=Lay_over9[0:30]
df9['Price']=price9[0:30]
df9['Duration']=Dur9[0:30]
df9

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,Vistara,09:40,12:05,New Delhi,Guwahati,Non stop,"₹ 2,591",02 h 25 m Non stop
1,Vistara,15:00,17:30,New Delhi,Guwahati,Non stop,"₹ 2,591",02 h 30 m Non stop
2,AirAsia,05:45,08:15,New Delhi,Guwahati,Non stop,"₹ 2,924",02 h 30 m Non stop
3,AirAsia,07:10,09:25,New Delhi,Guwahati,Non stop,"₹ 2,924",02 h 15 m Non stop
4,IndiGo,07:10,09:30,New Delhi,Guwahati,Non stop,"₹ 2,924",02 h 20 m Non stop
5,AirAsia,12:50,15:10,New Delhi,Guwahati,Non stop,"₹ 2,924",02 h 20 m Non stop
6,IndiGo,15:30,17:50,New Delhi,Guwahati,Non stop,"₹ 2,924",02 h 20 m Non stop
7,IndiGo,17:35,19:55,New Delhi,Guwahati,Non stop,"₹ 2,924",02 h 20 m Non stop
8,AirAsia,18:45,21:10,New Delhi,Guwahati,Non stop,"₹ 2,924",02 h 25 m Non stop
9,Go First,10:50,15:00,New Delhi,Guwahati,1 stop via Aizawl,"₹ 3,302",04 h 10 m 1 stop via Aizawl
10,IndiGo,07:50,10:10,New Delhi,Guwahati,Non stop,"₹ 3,390",02 h 20 m Non stop
11,IndiGo,12:30,14:55,New Delhi,Guwahati,Non stop,"₹ 3,390",02 h 25 m Non stop
12,Air India,16:15,18:45,New Delhi,Guwahati,Non stop,"₹ 3,890",02 h 30 m Non stop
13,Spicejet,10:15,12:35,New Delhi,Guwahati,Non stop,"₹ 4,115",02 h 20 m Non stop
14,Go First,13:00,15:20,New Delhi,Guwahati,Non stop,"₹ 4,151",02 h 20 m Non stop

In [25]:
df9.to_csv('flight_price09.csv',index='False')

In [26]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=GAU-DEL-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635287365464&forwardFlowRequired=true&mpo='
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name10=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines10=[]
for i in name10:
    Airlines10.append(i.get_text())
    
print(len(Airlines9))  

dep_time10=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep10, arr10 =dep_time10[::2], dep_time10[1::2]
DEP10=[]
for i in dep10:
    DEP10.append(i.get_text())
    ARV10=[]
for i in arr10:
    ARV10.append( i.get_text())
print(len(DEP10),len(ARV10))

layover10=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over10=[]
for l in layover10:
    Lay_over10.append(l.get_text())

dep_place10=soup.find_all('p', class_='darkText')
dep_place10, arr_place10 =dep_place10[::2], dep_place10[1::2]
origin10=[]
for i in dep_place10:
    origin10.append(i.get_text())
    destination10=[]
for i in arr_place10:
    destination10.append(i.get_text())
print(len(origin10),len(destination10))

price10=[]
pri10=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri10:
    price10.append(i.get_text())
    print(len(price10))


dur10=soup.find_all('div',class_="stop-info flexOne")
Dur10=[]
for i in dur10:
    soup.find_all('p')
    Dur10.append(i.get_text())
    print(len(Dur10))

15
16 16
16 16
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16

In [27]:
df10=pd.DataFrame()
df10['Airline_name']= Airlines10[0:24]
df10['Departure']=DEP10[0:24]
df10['Arrival']=ARV10[0:24]
df10['Source']=origin10[0:24]
df10['Destination']=destination10[0:24]
df10['Lay_over']=Lay_over10[0:24]
df10['Price']=price10[0:24]
df10['Duration']=Dur10[0:24]
df10

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,Vistara,12:40,15:35,Guwahati,New Delhi,Non stop,"₹ 3,248",02 h 55 m Non stop
1,IndiGo,06:25,09:15,Guwahati,New Delhi,Non stop,"₹ 3,273",02 h 50 m Non stop
2,AirAsia,08:55,11:50,Guwahati,New Delhi,Non stop,"₹ 3,273",02 h 55 m Non stop
3,IndiGo,12:35,15:35,Guwahati,New Delhi,Non stop,"₹ 3,273",03 h Non stop
4,AirAsia,12:40,15:30,Guwahati,New Delhi,Non stop,"₹ 3,273",02 h 50 m Non stop
5,Go First,15:55,18:55,Guwahati,New Delhi,Non stop,"₹ 3,273",03 h Non stop
6,IndiGo,18:20,21:10,Guwahati,New Delhi,Non stop,"₹ 3,273",02 h 50 m Non stop
7,AirAsia,18:50,21:35,Guwahati,New Delhi,Non stop,"₹ 3,273",02 h 45 m Non stop
8,IndiGo,20:30,23:20,Guwahati,New Delhi,Non stop,"₹ 3,273",02 h 50 m Non stop
9,AirAsia,21:40,00:35,Guwahati,New Delhi,Non stop,"₹ 3,273",02 h 55 m Non stop
10,Vistara,18:05,20:40,Guwahati,New Delhi,Non stop,"₹ 3,352",02 h 35 m Non stop
11,Spicejet,16:00,19:05,Guwahati,New Delhi,Non stop,"₹ 3,404",03 h 05 m Non stop
12,IndiGo,10:40,13:35,Guwahati,New Delhi,Non stop,"₹ 3,489",02 h 55 m Non stop
13,Air India,19:20,22:05,Guwahati,New Delhi,Non stop,"₹ 3,739",02 h 45 m Non stop
14,Go First,15:30,18:15,Guwahati,New Delhi,Non stop,"₹ 3,788",02 h 45 m Non stop
15,Air India,11:40,18:00,Guwahati,New Delhi,1 stop via Kolkata,"₹ 4,101",06 h 20 m 1 stop via Kolkata

In [28]:
df10.to_csv('flight_price010.csv',index='False')

In [29]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-BOM-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635288889189&forwardFlowRequired=true&mpo=&intl=false'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name11=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines11=[]
for i in name11:
    Airlines11.append(i.get_text())
    
print(len(Airlines11))  

dep_time11=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep11, arr11 =dep_time11[::2], dep_time11[1::2]
DEP11=[]
for i in dep11:
    DEP11.append(i.get_text())
    ARV11=[]
for i in arr11:
    ARV11.append( i.get_text())
print(len(DEP11),len(ARV11))

layover11=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over11=[]
for l in layover11:
    Lay_over11.append(l.get_text())

dep_place11=soup.find_all('p', class_='darkText')
dep_place11, arr_place11 =dep_place11[::2], dep_place11[1::2]
origin11=[]
for i in dep_place11:
    origin11.append(i.get_text())
    destination11=[]
for i in arr_place11:
    destination11.append(i.get_text())
print(len(origin11),len(destination11))

price11=[]
pri11=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri11:
    price11.append(i.get_text())
    print(len(price11))


dur11=soup.find_all('div',class_="stop-info flexOne")
Dur11=[]
for i in dur11:
    soup.find_all('p')
    Dur11.append(i.get_text())
    print(len(Dur11))

39
39 39
39 39
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39

In [30]:
df11=pd.DataFrame()
df11['Airline_name']= Airlines11[0:39]
df11['Departure']=DEP11[0:39]
df11['Arrival']=ARV11[0:39]
df11['Source']=origin11[0:39]
df11['Destination']=destination11[0:39]
df11['Lay_over']=Lay_over11[0:39]
df11['Price']=price11[0:39]
df11['Duration']=Dur11[0:39]
df11

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,IndiGo,01:05,03:20,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 15 m Non stop
1,Go First,02:00,04:15,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 15 m Non stop
2,AirAsia,04:25,06:35,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 10 m Non stop
3,Go First,07:00,09:10,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 10 m Non stop
4,Go First,08:00,10:10,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 10 m Non stop
5,IndiGo,09:30,11:45,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 15 m Non stop
6,IndiGo,10:45,13:05,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 20 m Non stop
7,IndiGo,16:00,18:15,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 15 m Non stop
8,Go First,18:05,20:25,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 20 m Non stop
9,Go First,19:40,21:55,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 15 m Non stop
10,Go First,21:00,23:15,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 15 m Non stop
11,Go First,22:30,00:40,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 10 m Non stop
12,Air India,08:00,10:10,New Delhi,Mumbai,Non stop,"₹ 2,476",02 h 10 m Non stop
13,Air India,15:05,18:15,New Delhi,Mumbai,1 stop via Indore,"₹ 2,476",03 h 10 m 1 stop via Indore
14,Air India,17:50,21:35,New Delhi,Mumbai,1 stop via Aurangabad,"₹ 2,476",03 h 45 m 1 stop via Aurangabad
15,Vistara,06:00,08:00,New Delhi,Mumbai,Non stop,"₹ 2,556",02 h Non stop
16,Vistara,21:40,23:50,New Delhi,Mumbai,Non stop,"₹ 2,556",02 h 10 m Non stop
17,Spicejet,06:20,08:40,New Delhi,Mumbai,Non stop,"₹ 2,621",02 h 20 m Non stop
18,Spicejet,07:20,09:35,New Delhi,Mumbai,Non stop,"₹ 2,621",02 h 15 m Non stop
19,Spicejet,18:55,21:05,New Delhi,Mumbai,Non stop,"₹ 2,621",02 h 10 m Non stop
20,Spicejet,19:45,22:05,New Delhi,Mumbai,Non stop,"₹ 2,621",02 h 20 m Non stop
21,AirAsia,20:00,22:15,New Delhi,Mumbai,Non stop,"₹ 2,757",02 h 15 m Non stop
22,Vistara,20:40,22:50,New Delhi,Mumbai,Non stop,"₹ 2,763",02 h 10 m Non stop
23,Go First,10:30,12:50,New Delhi,Mumbai,Non stop,"₹ 2,790",02 h 20 m Non stop
24,Go First,15:00,17:15,New Delhi,Mumbai,Non stop,"₹ 2,790",02 h 15 m Non stop
25,Air India,07:00,09:05,New Delhi,Mumbai,Non stop,"₹ 2,791",02 h 05 m Non stop
26,Air India,09:00,11:15,New Delhi,Mumbai,Non stop,"₹ 2,791",02 h 15 m Non stop
27,Air India,10:40,12:50,New Delhi,Mumbai,Non stop,"₹ 2,791",02 h 10 m Non stop
28,IndiGo,12:00,14:10,New Delhi,Mumbai,Non stop,"₹ 2,791",02 h 10 m Non stop
29,Vistara,09:30,11:40,New Delhi,Mumbai,Non stop,"₹ 3,081",02 h 10 m Non stop
30,Vistara,10:20,12:35,New Delhi,Mumbai,Non stop,"₹ 3,081",02 h 15 m Non stop
31,Vistara,11:40,14:00,New Delhi,Mumbai,Non stop,"₹ 3,081",02 h 20 m Non stop
32,Vistara,12:50,15:00,New Delhi,Mumbai,Non stop,"₹ 3,081",02 h 10 m Non stop
33,Vistara,15:30,17:40,New Delhi,Mumbai,Non stop,"₹ 3,081",02 h 10 m Non stop
34,Vistara,16:55,19:05,New Delhi,Mumbai,Non stop,"₹ 3,081",02 h 10 m Non stop
35,Vistara,19:50,22:00,New Delhi,Mumbai,Non stop,"₹ 3,081",02 h 10 m Non stop
36,Spicejet,19:00,23:50,New Delhi,Mumbai,1 stop via Jaipur,"₹ 3,533",04 h 50 m 1 stop via Jaipur
37,Go First,14:20,16:35,New Delhi,Mumbai,Non stop,"₹ 3,569",02 h 15 m Non stop
38,IndiGo,11:25,16:40,New Delhi,Mumbai,1 stop via Ahmedabad,"₹ 3,594",05 h 15 m 1 stop via Ahmedabad

In [31]:
df11.to_csv('flight_price011.csv',index='False')

In [32]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=BOM-GOI-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635289265544&forwardFlowRequired=true&mpo=&intl=false'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name12=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines12=[]
for i in name12:
    Airlines12.append(i.get_text())
    
print(len(Airlines12))  

dep_time12=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep12, arr12 =dep_time12[::2], dep_time12[1::2]
DEP12=[]
for i in dep12:
    DEP12.append(i.get_text())
    ARV12=[]
for i in arr12:
    ARV12.append( i.get_text())
print(len(DEP12),len(ARV12))

layover12=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over12=[]
for l in layover12:
    Lay_over12.append(l.get_text())

dep_place12=soup.find_all('p', class_='darkText')
dep_place12, arr_place12 =dep_place12[::2], dep_place12[1::2]
origin12=[]
for i in dep_place12:
    origin12.append(i.get_text())
    destination12=[]
for i in arr_place12:
    destination12.append(i.get_text())
print(len(origin12),len(destination12))

price12=[]
pri12=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri12:
    price12.append(i.get_text())
    print(len(price12))


dur12=soup.find_all('div',class_="stop-info flexOne")
Dur12=[]
for i in dur12:
    soup.find_all('p')
    Dur12.append(i.get_text())
    print(len(Dur12))

35
35 35
35 35
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35

In [33]:
df12=pd.DataFrame()
df12['Airline_name']= Airlines12[0:23]
df12['Departure']=DEP12[0:23]
df12['Arrival']=ARV12[0:23]
df12['Source']=origin12[0:23]
df12['Destination']=destination12[0:23]
df12['Lay_over']=Lay_over12[0:23]
df12['Price']=price12[0:23]
df12['Duration']=Dur12[0:23]
df12

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,AirAsia,04:45,05:55,Mumbai,Goa,Non stop,"₹ 2,019",01 h 10 m Non stop
1,AirAsia,23:35,00:35,Mumbai,Goa,Non stop,"₹ 2,019",01 h Non stop
2,Spicejet,23:45,01:00,Mumbai,Goa,Non stop,"₹ 2,384",01 h 15 m Non stop
3,Go First,22:05,23:25,Mumbai,Goa,Non stop,"₹ 2,418",01 h 20 m Non stop
4,Air India,21:00,22:35,Mumbai,Goa,Non stop,"₹ 2,625",01 h 35 m Non stop
5,IndiGo,11:30,12:35,Mumbai,Goa,Non stop,"₹ 2,688",01 h 05 m Non stop
6,Spicejet,15:30,17:05,Mumbai,Goa,Non stop,"₹ 2,804",01 h 35 m Non stop
7,Go First,15:20,16:30,Mumbai,Goa,Non stop,"₹ 2,842",01 h 10 m Non stop
8,Go First,16:20,17:45,Mumbai,Goa,Non stop,"₹ 2,842",01 h 25 m Non stop
9,IndiGo,12:00,13:10,Mumbai,Goa,Non stop,"₹ 3,735",01 h 10 m Non stop
10,Air India,05:30,06:50,Mumbai,Goa,Non stop,"₹ 3,780",01 h 20 m Non stop
11,Spicejet,11:15,12:50,Mumbai,Goa,Non stop,"₹ 3,958",01 h 35 m Non stop
12,AirAsia,13:05,22:00,Mumbai,Goa,1 stop via Bengaluru,"₹ 4,670",08 h 55 m 1 stop via Bengaluru
13,IndiGo,00:05,01:15,Mumbai,Goa,Non stop,"₹ 5,100",01 h 10 m Non stop
14,IndiGo,16:55,18:00,Mumbai,Goa,Non stop,"₹ 5,100",01 h 05 m Non stop
15,AirAsia,02:35,07:00,Mumbai,Goa,1 stop via Bengaluru,"₹ 5,300",04 h 25 m 1 stop via Bengaluru
16,AirAsia,21:20,07:00,Mumbai,Goa,1 stop via Bengaluru,"₹ 5,300",09 h 40 m 1 stop via Bengaluru
17,Air India,19:05,20:30,Mumbai,Goa,Non stop,"₹ 5,471",01 h 25 m Non stop
18,Go First,07:30,12:40,Mumbai,Goa,1 stop via Ahmedabad,"₹ 5,599",05 h 10 m 1 stop via Ahmedabad
19,Go First,22:40,12:40,Mumbai,Goa,1 stop via Ahmedabad,"₹ 5,599",14 h 1 stop via Ahmedabad
20,IndiGo,05:15,06:25,Mumbai,Goa,Non stop,"₹ 5,628",01 h 10 m Non stop
21,Go First,04:55,06:10,Mumbai,Goa,Non stop,"₹ 5,887",01 h 15 m Non stop
22,Vistara,11:25,12:45,Mumbai,Goa,Non stop,"₹ 5,996",01 h 20 m Non stop

In [34]:
df12.to_csv('flight_price012.csv',index='False')

In [35]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=PNQ-JAI-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635289570575&forwardFlowRequired=true&mpo=&intl=false'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name13=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines13=[]
for i in name13:
    Airlines13.append(i.get_text())
    
print(len(Airlines13))  

dep_time13=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep13, arr13 =dep_time13[::2], dep_time13[1::2]
DEP13=[]
for i in dep13:
    DEP13.append(i.get_text())
    ARV13=[]
for i in arr13:
    ARV13.append( i.get_text())
print(len(DEP13),len(ARV13))

layover13=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over13=[]
for l in layover13:
    Lay_over13.append(l.get_text())

dep_place13=soup.find_all('p', class_='darkText')
dep_place13, arr_place13 =dep_place13[::2], dep_place13[1::2]
origin13=[]
for i in dep_place13:
    origin13.append(i.get_text())
    destination13=[]
for i in arr_place13:
    destination13.append(i.get_text())
print(len(origin13),len(destination13))

price13=[]
pri13=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri13:
    price13.append(i.get_text())
    print(len(price13))


dur13=soup.find_all('div',class_="stop-info flexOne")
Dur13=[]
for i in dur13:
    soup.find_all('p')
    Dur13.append(i.get_text())
    print(len(Dur13))

19
19 19
19 19
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19

In [36]:
df13=pd.DataFrame()
df13['Airline_name']= Airlines13[0:19]
df13['Departure']=DEP13[0:19]
df13['Arrival']=ARV13[0:19]
df13['Source']=origin13[0:19]
df13['Destination']=destination13[0:19]
df13['Lay_over']=Lay_over13[0:19]
df13['Price']=price13[0:19]
df13['Duration']=Dur13[0:19]
df13

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,AirAsia,18:40,23:20,Pune,Jaipur,1 stop via New Delhi,"₹ 4,180",04 h 40 m 1 stop via New Delhi
1,AirAsia,17:50,23:20,Pune,Jaipur,1 stop via New Delhi,"₹ 4,180",05 h 30 m 1 stop via New Delhi
2,AirAsia,14:55,16:45,Pune,Jaipur,Non stop,"₹ 4,332",01 h 50 m Non stop
3,IndiGo,19:15,21:10,Pune,Jaipur,Non stop,"₹ 4,512",01 h 55 m Non stop
4,IndiGo,16:15,22:50,Pune,Jaipur,1 stop via New Delhi,"₹ 4,740",06 h 35 m 1 stop via New Delhi
5,IndiGo,13:45,22:50,Pune,Jaipur,1 stop via New Delhi,"₹ 4,740",09 h 05 m 1 stop via New Delhi
6,Go First,23:15,12:10,Pune,Jaipur,1 stop via Ahmedabad,"₹ 4,805",12 h 55 m 1 stop via Ahmedabad
7,Go First,19:00,10:45,Pune,Jaipur,1 stop via Bengaluru,"₹ 4,877",15 h 45 m 1 stop via Bengaluru
8,Air India,08:45,14:00,Pune,Jaipur,1 stop via New Delhi,"₹ 5,675",05 h 15 m 1 stop via New Delhi
9,Air India,18:50,07:10,Pune,Jaipur,1 stop via New Delhi,"₹ 5,685",12 h 20 m 1 stop via New Delhi
10,IndiGo,11:30,16:55,Pune,Jaipur,1 stop via Ahmedabad,"₹ 6,875",05 h 25 m 1 stop via Ahmedabad
11,IndiGo,14:00,21:35,Pune,Jaipur,1 stop via Bengaluru,"₹ 7,338",07 h 35 m 1 stop via Bengaluru
12,IndiGo,18:15,00:25,Pune,Jaipur,1 stop via Bengaluru,"₹ 7,338",06 h 10 m 1 stop via Bengaluru
13,IndiGo,11:10,18:00,Pune,Jaipur,1 stop via Bengaluru,"₹ 7,598",06 h 50 m 1 stop via Bengaluru
14,IndiGo,08:10,18:00,Pune,Jaipur,1 stop via Bengaluru,"₹ 7,598",09 h 50 m 1 stop via Bengaluru
15,IndiGo,08:15,13:50,Pune,Jaipur,1 stop via New Delhi,"₹ 8,836",05 h 35 m 1 stop via New Delhi
16,IndiGo,15:35,22:20,Pune,Jaipur,1 stop via Hyderabad,"₹ 8,846",06 h 45 m 1 stop via Hyderabad
17,IndiGo,13:40,22:20,Pune,Jaipur,1 stop via Hyderabad,"₹ 8,846",08 h 40 m 1 stop via Hyderabad
18,Air India,16:20,07:10,Pune,Jaipur,"3 stop via Nasik,Ahmedabad,New Delhi","₹ 9,045","14 h 50 m 3 stop via Nasik,Ahmedabad,New Delhi"

In [37]:
df13.to_csv('flight_price013.csv',index='False')

In [38]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=PNQ-HYD-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635289869692&forwardFlowRequired=true&mpo=&intl=false'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name14=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines14=[]
for i in name14:
    Airlines14.append(i.get_text())
    
print(len(Airlines14))  

dep_time14=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep14, arr14 =dep_time14[::2], dep_time14[1::2]
DEP14=[]
for i in dep14:
    DEP14.append(i.get_text())
    ARV14=[]
for i in arr14:
    ARV14.append( i.get_text())
print(len(DEP14),len(ARV14))

layover14=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over14=[]
for l in layover14:
    Lay_over14.append(l.get_text())

dep_place14=soup.find_all('p', class_='darkText')
dep_place14, arr_place14 =dep_place14[::2], dep_place14[1::2]
origin14=[]
for i in dep_place14:
    origin14.append(i.get_text())
    destination14=[]
for i in arr_place14:
    destination14.append(i.get_text())
print(len(origin14),len(destination14))

price14=[]
pri14=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri14:
    price14.append(i.get_text())
    print(len(price14))


dur14=soup.find_all('div',class_="stop-info flexOne")
Dur14=[]
for i in dur14:
    soup.find_all('p')
    Dur14.append(i.get_text())
    print(len(Dur14))

39
39 39
39 39
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39

In [40]:
df14=pd.DataFrame()
df14['Airline_name']= Airlines14[0:39]
df14['Departure']=DEP14[0:39]
df14['Arrival']=ARV14[0:39]
df14['Source']=origin14[0:39]
df14['Destination']=destination14[0:39]
df14['Lay_over']=Lay_over14[0:39]
df14['Price']=price14[0:39]
df14['Duration']=Dur14[0:39]
df14

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,Go First,19:00,00:05,Pune,Hyderabad,1 stop via Bengaluru,"₹ 3,379",05 h 05 m 1 stop via Bengaluru
1,Go First,17:40,00:05,Pune,Hyderabad,1 stop via Bengaluru,"₹ 3,379",06 h 25 m 1 stop via Bengaluru
2,Go First,19:00,08:30,Pune,Hyderabad,1 stop via Bengaluru,"₹ 3,379",13 h 30 m 1 stop via Bengaluru
3,IndiGo,14:00,20:05,Pune,Hyderabad,1 stop via Bengaluru,"₹ 3,432",06 h 05 m 1 stop via Bengaluru
4,IndiGo,14:00,21:30,Pune,Hyderabad,1 stop via Bengaluru,"₹ 3,432",07 h 30 m 1 stop via Bengaluru
5,IndiGo,18:15,23:10,Pune,Hyderabad,1 stop via Bengaluru,"₹ 3,432",04 h 55 m 1 stop via Bengaluru
6,IndiGo,14:00,23:10,Pune,Hyderabad,1 stop via Bengaluru,"₹ 3,432",09 h 10 m 1 stop via Bengaluru
7,IndiGo,18:15,01:00,Pune,Hyderabad,1 stop via Bengaluru,"₹ 3,432",06 h 45 m 1 stop via Bengaluru
8,IndiGo,13:40,14:50,Pune,Hyderabad,Non stop,"₹ 3,648",01 h 10 m Non stop
9,IndiGo,15:35,16:40,Pune,Hyderabad,Non stop,"₹ 3,648",01 h 05 m Non stop
10,IndiGo,08:10,14:15,Pune,Hyderabad,1 stop via Bengaluru,"₹ 3,692",06 h 05 m 1 stop via Bengaluru
11,IndiGo,11:10,17:50,Pune,Hyderabad,1 stop via Bengaluru,"₹ 3,692",06 h 40 m 1 stop via Bengaluru
12,IndiGo,08:10,17:50,Pune,Hyderabad,1 stop via Bengaluru,"₹ 3,692",09 h 40 m 1 stop via Bengaluru
13,IndiGo,11:10,20:05,Pune,Hyderabad,1 stop via Bengaluru,"₹ 3,692",08 h 55 m 1 stop via Bengaluru
14,IndiGo,11:10,21:30,Pune,Hyderabad,1 stop via Bengaluru,"₹ 3,692",10 h 20 m 1 stop via Bengaluru
15,AirAsia,19:25,06:35,Pune,Hyderabad,1 stop via Bengaluru,"₹ 3,969",11 h 10 m 1 stop via Bengaluru
16,IndiGo,14:40,20:55,Pune,Hyderabad,1 stop via Chennai,"₹ 4,444",06 h 15 m 1 stop via Chennai
17,IndiGo,11:05,17:25,Pune,Hyderabad,1 stop via Nagpur,"₹ 4,490",06 h 20 m 1 stop via Nagpur
18,IndiGo,09:35,18:10,Pune,Hyderabad,1 stop via Chennai,"₹ 4,589",08 h 35 m 1 stop via Chennai
19,IndiGo,09:35,17:05,Pune,Hyderabad,1 stop via Chennai,"₹ 5,009",07 h 30 m 1 stop via Chennai
20,Go First,19:10,09:30,Pune,Hyderabad,1 stop via New Delhi,"₹ 5,397",14 h 20 m 1 stop via New Delhi
21,IndiGo,14:40,22:20,Pune,Hyderabad,1 stop via Chennai,"₹ 5,414",07 h 40 m 1 stop via Chennai
22,IndiGo,13:45,20:00,Pune,Hyderabad,1 stop via New Delhi,"₹ 5,475",06 h 15 m 1 stop via New Delhi
23,IndiGo,13:45,21:50,Pune,Hyderabad,1 stop via New Delhi,"₹ 5,475",08 h 05 m 1 stop via New Delhi
24,IndiGo,16:15,23:30,Pune,Hyderabad,1 stop via New Delhi,"₹ 5,475",07 h 15 m 1 stop via New Delhi
25,IndiGo,13:45,23:30,Pune,Hyderabad,1 stop via New Delhi,"₹ 5,475",09 h 45 m 1 stop via New Delhi
26,IndiGo,16:15,01:15,Pune,Hyderabad,1 stop via New Delhi,"₹ 5,475",09 h 1 stop via New Delhi
27,IndiGo,13:45,01:15,Pune,Hyderabad,1 stop via New Delhi,"₹ 5,475",11 h 30 m 1 stop via New Delhi
28,Go First,15:30,21:50,Pune,Hyderabad,1 stop via New Delhi,"₹ 5,713",06 h 20 m 1 stop via New Delhi
29,Air India,18:50,10:30,Pune,Hyderabad,1 stop via New Delhi,"₹ 5,843",15 h 40 m 1 stop via New Delhi
30,IndiGo,09:35,19:30,Pune,Hyderabad,1 stop via Chennai,"₹ 5,849",09 h 55 m 1 stop via Chennai
31,IndiGo,14:40,19:30,Pune,Hyderabad,1 stop via Chennai,"₹ 6,674",04 h 50 m 1 stop via Chennai
32,IndiGo,14:40,23:55,Pune,Hyderabad,1 stop via Chennai,"₹ 6,674",09 h 15 m 1 stop via Chennai
33,IndiGo,11:30,20:20,Pune,Hyderabad,1 stop via Ahmedabad,"₹ 6,875",08 h 50 m 1 stop via Ahmedabad
34,IndiGo,16:40,00:30,Pune,Hyderabad,1 stop via Ahmedabad,"₹ 6,875",07 h 50 m 1 stop via Ahmedabad
35,IndiGo,19:15,06:55,Pune,Hyderabad,1 stop via Jaipur,"₹ 7,118",11 h 40 m 1 stop via Jaipur
36,IndiGo,17:25,18:45,Pune,Hyderabad,Non stop,"₹ 7,519",01 h 20 m Non stop
37,IndiGo,17:45,22:20,Pune,Hyderabad,1 stop via Chennai,"₹ 7,638",04 h 35 m 1 stop via Chennai
38,IndiGo,09:45,18:55,Pune,Hyderabad,1 stop via Kochi,"₹ 7,848",09 h 10 m 1 stop via Kochi

In [41]:
df14.to_csv('flight_price014.csv',index='False')

In [42]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-TRZ-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635366450239&forwardFlowRequired=true&mpo=&intl=false'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name15=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines15=[]
for i in name15:
    Airlines15.append(i.get_text())
    
print(len(Airlines15))  

dep_time15=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep15, arr15 =dep_time15[::2], dep_time15[1::2]
DEP15=[]
for i in dep15:
    DEP15.append(i.get_text())
    ARV15=[]
for i in arr15:
    ARV15.append( i.get_text())
print(len(DEP15),len(ARV15))

layover15=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over15=[]
for l in layover15:
    Lay_over15.append(l.get_text())

dep_place15=soup.find_all('p', class_='darkText')
dep_place15, arr_place15 =dep_place15[::2], dep_place15[1::2]
origin15=[]
for i in dep_place15:
    origin15.append(i.get_text())
    destination15=[]
for i in arr_place15:
    destination15.append(i.get_text())
print(len(origin15),len(destination15))

price15=[]
pri15=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri15:
    price15.append(i.get_text())
    print(len(price15))


dur15=soup.find_all('div',class_="stop-info flexOne")
Dur15=[]
for i in dur15:
    soup.find_all('p')
    Dur15.append(i.get_text())
    print(len(Dur15))

16
16 16
16 16
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16

In [43]:
df15=pd.DataFrame()
df15['Airline_name']= Airlines15[0:19]
df15['Departure']=DEP15[0:19]
df15['Arrival']=ARV15[0:19]
df15['Source']=origin15[0:19]
df15['Destination']=destination15[0:19]
df15['Lay_over']=Lay_over15[0:19]
df15['Price']=price15[0:19]
df15['Duration']=Dur15[0:19]
df15

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,"Go First, IndiGo",02:00,11:10,New Delhi,Tiruchirappalli,"2 stop via Mumbai,Chennai","₹ 5,857","09 h 10 m 2 stop via Mumbai,Chennai"
1,IndiGo,02:30,08:45,New Delhi,Tiruchirappalli,1 stop via Bengaluru,"₹ 6,615",06 h 15 m 1 stop via Bengaluru
2,IndiGo,22:50,08:45,New Delhi,Tiruchirappalli,1 stop via Bengaluru,"₹ 6,615",09 h 55 m 1 stop via Bengaluru
3,IndiGo,21:25,08:45,New Delhi,Tiruchirappalli,1 stop via Bengaluru,"₹ 6,615",11 h 20 m 1 stop via Bengaluru
4,"Vistara, IndiGo",07:20,22:00,New Delhi,Tiruchirappalli,"2 stop via Chennai,Bengaluru","₹ 8,128","14 h 40 m 2 stop via Chennai,Bengaluru"
5,IndiGo,15:30,22:00,New Delhi,Tiruchirappalli,1 stop via Bengaluru,"₹ 8,243",06 h 30 m 1 stop via Bengaluru
6,IndiGo,12:00,22:00,New Delhi,Tiruchirappalli,1 stop via Bengaluru,"₹ 8,243",10 h 1 stop via Bengaluru
7,"Spicejet, IndiGo",06:15,22:00,New Delhi,Tiruchirappalli,"2 stop via Chennai,Bengaluru","₹ 8,317","15 h 45 m 2 stop via Chennai,Bengaluru"
8,"Air India, IndiGo",09:45,22:00,New Delhi,Tiruchirappalli,"2 stop via Chennai,Bengaluru","₹ 8,722","12 h 15 m 2 stop via Chennai,Bengaluru"
9,"Vistara, IndiGo",07:20,21:10,New Delhi,Tiruchirappalli,1 stop via Chennai,"₹ 9,889",13 h 50 m 1 stop via Chennai
10,"Air India, IndiGo",09:45,21:10,New Delhi,Tiruchirappalli,1 stop via Chennai,"₹ 9,905",11 h 25 m 1 stop via Chennai
11,IndiGo,13:00,20:05,New Delhi,Tiruchirappalli,1 stop via Hyderabad,"₹ 10,162",07 h 05 m 1 stop via Hyderabad
12,IndiGo,11:00,20:05,New Delhi,Tiruchirappalli,1 stop via Hyderabad,"₹ 10,162",09 h 05 m 1 stop via Hyderabad
13,IndiGo,09:40,20:05,New Delhi,Tiruchirappalli,1 stop via Hyderabad,"₹ 10,162",10 h 25 m 1 stop via Hyderabad
14,IndiGo,07:55,20:05,New Delhi,Tiruchirappalli,1 stop via Hyderabad,"₹ 10,162",12 h 10 m 1 stop via Hyderabad
15,"AirAsia, IndiGo",09:35,21:10,New Delhi,Tiruchirappalli,"2 stop via Bengaluru,Chennai","₹ 12,840","11 h 35 m 2 stop via Bengaluru,Chennai"

In [44]:
df15.to_csv('flight_price015.csv',index='False')

In [45]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=PAT-GOI-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635366562672&forwardFlowRequired=true&mpo=&intl=false'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name16=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines16=[]
for i in name16:
    Airlines16.append(i.get_text())
    
print(len(Airlines16))  

dep_time16=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep16, arr16 =dep_time16[::2], dep_time16[1::2]
DEP16=[]
for i in dep16:
    DEP16.append(i.get_text())
    ARV16=[]
for i in arr16:
    ARV16.append( i.get_text())
print(len(DEP16),len(ARV16))

layover16=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over16=[]
for l in layover16:
    Lay_over16.append(l.get_text())

dep_place16=soup.find_all('p', class_='darkText')
dep_place16, arr_place16 =dep_place16[::2], dep_place16[1::2]
origin16=[]
for i in dep_place16:
    origin16.append(i.get_text())
    destination16=[]
for i in arr_place16:
    destination16.append(i.get_text())
print(len(origin16),len(destination16))

price16=[]
pri16=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri16:
    price16.append(i.get_text())
    print(len(price16))


dur16=soup.find_all('div',class_="stop-info flexOne")
Dur16=[]
for i in dur16:
    soup.find_all('p')
    Dur16.append(i.get_text())
    print(len(Dur16))

18
18 18
18 18
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18

In [46]:
df16=pd.DataFrame()
df16['Airline_name']= Airlines16[0:19]
df16['Departure']=DEP16[0:19]
df16['Arrival']=ARV16[0:19]
df16['Source']=origin16[0:19]
df16['Destination']=destination16[0:19]
df16['Lay_over']=Lay_over16[0:19]
df16['Price']=price16[0:19]
df16['Duration']=Dur16[0:19]
df16

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,Spicejet,22:10,01:00,Patna,Goa,1 stop via Mumbai,"₹ 5,842",26 h 50 m 1 stop via Mumbai
1,Go First,14:20,23:25,Patna,Goa,1 stop via Mumbai,"₹ 5,878",09 h 05 m 1 stop via Mumbai
2,IndiGo,11:45,18:25,Patna,Goa,1 stop via Bengaluru,"₹ 5,953",06 h 40 m 1 stop via Bengaluru
3,IndiGo,10:45,17:25,Patna,Goa,1 stop via Hyderabad,"₹ 6,161",06 h 40 m 1 stop via Hyderabad
4,IndiGo,15:30,00:20,Patna,Goa,1 stop via New Delhi,"₹ 6,333",08 h 50 m 1 stop via New Delhi
5,IndiGo,19:10,03:00,Patna,Goa,1 stop via Kolkata,"₹ 6,333",07 h 50 m 1 stop via Kolkata
6,IndiGo,16:20,03:00,Patna,Goa,1 stop via Kolkata,"₹ 6,333",10 h 40 m 1 stop via Kolkata
7,"Go First, IndiGo",14:45,21:15,Patna,Goa,1 stop via Bengaluru,"₹ 6,459",06 h 30 m 1 stop via Bengaluru
8,Spicejet,11:30,01:00,Patna,Goa,1 stop via Mumbai,"₹ 6,682",13 h 30 m 1 stop via Mumbai
9,IndiGo,19:25,02:00,Patna,Goa,1 stop via Bengaluru,"₹ 7,131",06 h 35 m 1 stop via Bengaluru
10,Spicejet,11:30,17:05,Patna,Goa,1 stop via Mumbai,"₹ 7,208",05 h 35 m 1 stop via Mumbai
11,"Go First, IndiGo",12:25,18:25,Patna,Goa,1 stop via Bengaluru,"₹ 7,409",06 h 1 stop via Bengaluru
12,Air India,19:10,00:35,Patna,Goa,1 stop via New Delhi,"₹ 7,562",05 h 25 m 1 stop via New Delhi
13,IndiGo,16:40,23:35,Patna,Goa,1 stop via Hyderabad,"₹ 7,675",06 h 55 m 1 stop via Hyderabad
14,Spicejet,09:30,19:00,Patna,Goa,1 stop via New Delhi,"₹ 7,727",09 h 30 m 1 stop via New Delhi
15,IndiGo,18:35,01:15,Patna,Goa,1 stop via Mumbai,"₹ 8,643",06 h 40 m 1 stop via Mumbai
16,Go First,17:10,23:10,Patna,Goa,1 stop via New Delhi,"₹ 8,887",06 h 1 stop via New Delhi
17,Go First,16:05,23:10,Patna,Goa,1 stop via New Delhi,"₹ 8,887",07 h 05 m 1 stop via New Delhi

In [47]:
df16.to_csv('flight_price016.csv',index='False')

In [48]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=AMD-CCU-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635368854371&forwardFlowRequired=true&mpo=&intl=false'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name17=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines17=[]
for i in name17:
    Airlines17.append(i.get_text())
    
print(len(Airlines17))  

dep_time17=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep17, arr17 =dep_time17[::2], dep_time17[1::2]
DEP17=[]
for i in dep17:
    DEP17.append(i.get_text())
    ARV17=[]
for i in arr17:
    ARV17.append( i.get_text())
print(len(DEP17),len(ARV17))

layover17=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over17=[]
for l in layover17:
    Lay_over17.append(l.get_text())

dep_place17=soup.find_all('p', class_='darkText')
dep_place17, arr_place17 =dep_place17[::2], dep_place17[1::2]
origin17=[]
for i in dep_place17:
    origin17.append(i.get_text())
    destination17=[]
for i in arr_place17:
    destination17.append(i.get_text())
print(len(origin17),len(destination17))

price17=[]
pri17=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri17:
    price17.append(i.get_text())
    print(len(price17))


dur17=soup.find_all('div',class_="stop-info flexOne")
Dur17=[]
for i in dur17:
    soup.find_all('p')
    Dur17.append(i.get_text())
    print(len(Dur17))

24
24 24
24 24
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24

In [49]:
df17=pd.DataFrame()
df17['Airline_name']= Airlines17[0:24]
df17['Departure']=DEP17[0:24]
df17['Arrival']=ARV17[0:24]
df17['Source']=origin17[0:24]
df17['Destination']=destination17[0:24]
df17['Lay_over']=Lay_over17[0:24]
df17['Price']=price17[0:24]
df17['Duration']=Dur17[0:24]
df17

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,Air India,19:55,08:50,Ahmedabad,Kolkata,1 stop via Mumbai,"₹ 5,178",12 h 55 m 1 stop via Mumbai
1,Go First,10:30,22:10,Ahmedabad,Kolkata,1 stop via Jaipur,"₹ 5,278",11 h 40 m 1 stop via Jaipur
2,IndiGo,11:00,20:00,Ahmedabad,Kolkata,1 stop via Chennai,"₹ 5,632",09 h 1 stop via Chennai
3,IndiGo,06:20,12:10,Ahmedabad,Kolkata,1 stop via New Delhi,"₹ 5,668",05 h 50 m 1 stop via New Delhi
4,IndiGo,08:45,17:20,Ahmedabad,Kolkata,1 stop via New Delhi,"₹ 5,668",08 h 35 m 1 stop via New Delhi
5,IndiGo,14:05,19:40,Ahmedabad,Kolkata,1 stop via New Delhi,"₹ 5,668",05 h 35 m 1 stop via New Delhi
6,IndiGo,15:40,21:55,Ahmedabad,Kolkata,1 stop via New Delhi,"₹ 5,668",06 h 15 m 1 stop via New Delhi
7,IndiGo,22:40,05:10,Ahmedabad,Kolkata,1 stop via New Delhi,"₹ 5,668",06 h 30 m 1 stop via New Delhi
8,IndiGo,20:30,05:10,Ahmedabad,Kolkata,1 stop via New Delhi,"₹ 5,668",08 h 40 m 1 stop via New Delhi
9,IndiGo,06:00,14:25,Ahmedabad,Kolkata,1 stop via Bengaluru,"₹ 5,742",08 h 25 m 1 stop via Bengaluru
10,IndiGo,15:45,22:45,Ahmedabad,Kolkata,1 stop via Bengaluru,"₹ 5,742",07 h 1 stop via Bengaluru
11,IndiGo,06:35,13:10,Ahmedabad,Kolkata,1 stop via Jaipur,"₹ 5,747",06 h 35 m 1 stop via Jaipur
12,Go First,00:35,07:30,Ahmedabad,Kolkata,1 stop via Mumbai,"₹ 5,807",06 h 55 m 1 stop via Mumbai
13,IndiGo,18:45,00:30,Ahmedabad,Kolkata,1 stop via Hyderabad,"₹ 5,847",05 h 45 m 1 stop via Hyderabad
14,IndiGo,22:45,06:05,Ahmedabad,Kolkata,1 stop via Hyderabad,"₹ 5,847",07 h 20 m 1 stop via Hyderabad
15,Go First,06:05,08:40,Ahmedabad,Kolkata,Non stop,"₹ 5,880",02 h 35 m Non stop
16,IndiGo,15:25,23:45,Ahmedabad,Kolkata,1 stop via Mumbai,"₹ 5,891",08 h 20 m 1 stop via Mumbai
17,IndiGo,06:25,08:55,Ahmedabad,Kolkata,Non stop,"₹ 5,901",02 h 30 m Non stop
18,IndiGo,09:20,11:45,Ahmedabad,Kolkata,Non stop,"₹ 5,901",02 h 25 m Non stop
19,IndiGo,20:05,22:25,Ahmedabad,Kolkata,Non stop,"₹ 5,901",02 h 20 m Non stop
20,Vistara,10:55,19:35,Ahmedabad,Kolkata,1 stop via New Delhi,"₹ 6,043",08 h 40 m 1 stop via New Delhi
21,Go First,10:35,16:15,Ahmedabad,Kolkata,1 stop via Varanasi,"₹ 6,618",05 h 40 m 1 stop via Varanasi
22,IndiGo,23:40,06:10,Ahmedabad,Kolkata,1 stop via Bengaluru,"₹ 7,364",06 h 30 m 1 stop via Bengaluru
23,IndiGo,15:10,20:20,Ahmedabad,Kolkata,1 stop via Jaipur,"₹ 7,739",05 h 10 m 1 stop via Jaipur

In [50]:
df17.to_csv('flight_price017.csv',index='False')

In [51]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=CCU-AMD-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635369200266&forwardFlowRequired=true&mpo='
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name18=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines18=[]
for i in name18:
    Airlines18.append(i.get_text())
    
print(len(Airlines18))  

dep_time18=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep18, arr18 =dep_time18[::2], dep_time18[1::2]
DEP18=[]
for i in dep18:
    DEP18.append(i.get_text())
    ARV18=[]
for i in arr18:
    ARV18.append( i.get_text())
print(len(DEP18),len(ARV18))

layover18=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over18=[]
for l in layover18:
    Lay_over18.append(l.get_text())

dep_place18=soup.find_all('p', class_='darkText')
dep_place18, arr_place18 =dep_place18[::2], dep_place18[1::2]
origin18=[]
for i in dep_place18:
    origin18.append(i.get_text())
    destination18=[]
for i in arr_place18:
    destination18.append(i.get_text())
print(len(origin18),len(destination18))

price18=[]
pri18=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri18:
    price18.append(i.get_text())
    print(len(price18))


dur18=soup.find_all('div',class_="stop-info flexOne")
Dur18=[]
for i in dur18:
    soup.find_all('p')
    Dur18.append(i.get_text())
    print(len(Dur18))

27
27 27
27 27
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27

In [52]:
df18=pd.DataFrame()
df18['Airline_name']= Airlines18[0:27]
df18['Departure']=DEP18[0:27]
df18['Arrival']=ARV18[0:27]
df18['Source']=origin18[0:27]
df18['Destination']=destination18[0:27]
df18['Lay_over']=Lay_over18[0:27]
df18['Price']=price18[0:27]
df18['Duration']=Dur18[0:27]
df18

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,Air India,15:30,20:40,Kolkata,Ahmedabad,1 stop via New Delhi,"₹ 5,105",05 h 10 m 1 stop via New Delhi
1,Air India,09:40,17:50,Kolkata,Ahmedabad,1 stop via Mumbai,"₹ 5,456",08 h 10 m 1 stop via Mumbai
2,Go First,20:00,10:00,Kolkata,Ahmedabad,1 stop via Hyderabad,"₹ 5,675",14 h 1 stop via Hyderabad
3,IndiGo,06:40,13:10,Kolkata,Ahmedabad,1 stop via New Delhi,"₹ 5,718",06 h 30 m 1 stop via New Delhi
4,IndiGo,05:30,13:10,Kolkata,Ahmedabad,1 stop via New Delhi,"₹ 5,718",07 h 40 m 1 stop via New Delhi
5,IndiGo,08:45,15:05,Kolkata,Ahmedabad,1 stop via New Delhi,"₹ 5,718",06 h 20 m 1 stop via New Delhi
6,IndiGo,11:25,19:55,Kolkata,Ahmedabad,1 stop via New Delhi,"₹ 5,718",08 h 30 m 1 stop via New Delhi
7,IndiGo,10:05,19:55,Kolkata,Ahmedabad,1 stop via New Delhi,"₹ 5,718",09 h 50 m 1 stop via New Delhi
8,IndiGo,21:40,06:50,Kolkata,Ahmedabad,1 stop via New Delhi,"₹ 5,718",09 h 10 m 1 stop via New Delhi
9,IndiGo,20:25,06:50,Kolkata,Ahmedabad,1 stop via New Delhi,"₹ 5,718",10 h 25 m 1 stop via New Delhi
10,IndiGo,11:40,20:15,Kolkata,Ahmedabad,1 stop via Lucknow,"₹ 5,789",08 h 35 m 1 stop via Lucknow
11,Vistara,10:15,19:40,Kolkata,Ahmedabad,1 stop via New Delhi,"₹ 6,006",09 h 25 m 1 stop via New Delhi
12,IndiGo,01:15,06:50,Kolkata,Ahmedabad,1 stop via New Delhi,"₹ 6,088",05 h 35 m 1 stop via New Delhi
13,IndiGo,05:35,08:20,Kolkata,Ahmedabad,Non stop,"₹ 6,174",02 h 45 m Non stop
14,IndiGo,16:35,19:35,Kolkata,Ahmedabad,Non stop,"₹ 6,174",03 h Non stop
15,IndiGo,21:20,00:05,Kolkata,Ahmedabad,Non stop,"₹ 6,174",02 h 45 m Non stop
16,IndiGo,16:10,23:10,Kolkata,Ahmedabad,1 stop via Bengaluru,"₹ 6,240",07 h 1 stop via Bengaluru
17,Go First,17:30,00:05,Kolkata,Ahmedabad,1 stop via Mumbai,"₹ 6,302",06 h 35 m 1 stop via Mumbai
18,Go First,14:20,21:30,Kolkata,Ahmedabad,1 stop via New Delhi,"₹ 6,316",07 h 10 m 1 stop via New Delhi
19,IndiGo,15:40,21:25,Kolkata,Ahmedabad,1 stop via Mumbai,"₹ 6,384",05 h 45 m 1 stop via Mumbai
20,IndiGo,23:35,07:35,Kolkata,Ahmedabad,1 stop via Bengaluru,"₹ 6,545",08 h 1 stop via Bengaluru
21,Go First,04:55,10:45,Kolkata,Ahmedabad,1 stop via Mumbai,"₹ 6,553",05 h 50 m 1 stop via Mumbai
22,IndiGo,18:05,23:50,Kolkata,Ahmedabad,1 stop via New Delhi,"₹ 6,558",05 h 45 m 1 stop via New Delhi
23,IndiGo,16:30,23:50,Kolkata,Ahmedabad,1 stop via New Delhi,"₹ 6,558",07 h 20 m 1 stop via New Delhi
24,Go First,16:25,19:30,Kolkata,Ahmedabad,Non stop,"₹ 6,805",03 h 05 m Non stop
25,Air India,10:25,18:10,Kolkata,Ahmedabad,1 stop via New Delhi,"₹ 7,245",07 h 45 m 1 stop via New Delhi
26,IndiGo,23:55,06:45,Kolkata,Ahmedabad,1 stop via Chennai,"₹ 7,634",06 h 50 m 1 stop via Chennai

In [53]:
df18.to_csv('flight_price018.csv',index='False')

In [54]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=CCU-GOI-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635369458881&forwardFlowRequired=true&mpo=&intl=false'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name19=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines19=[]
for i in name19:
    Airlines19.append(i.get_text())
    
print(len(Airlines19))  

dep_time19=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep19, arr19 =dep_time19[::2], dep_time19[1::2]
DEP19=[]
for i in dep19:
    DEP19.append(i.get_text())
    ARV19=[]
for i in arr19:
    ARV19.append( i.get_text())
print(len(DEP19),len(ARV19))

layover19=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over19=[]
for l in layover19:
    Lay_over19.append(l.get_text())

dep_place19=soup.find_all('p', class_='darkText')
dep_place19, arr_place19 =dep_place19[::2], dep_place19[1::2]
origin19=[]
for i in dep_place19:
    origin19.append(i.get_text())
    destination19=[]
for i in arr_place19:
    destination19.append(i.get_text())
print(len(origin19),len(destination19))

price19=[]
pri19=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri19:
    price19.append(i.get_text())
    print(len(price19))


dur19=soup.find_all('div',class_="stop-info flexOne")
Dur19=[]
for i in dur19:
    soup.find_all('p')
    Dur19.append(i.get_text())
    print(len(Dur19))

19
19 19
19 19
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19

In [55]:
df19=pd.DataFrame()
df19['Airline_name']= Airlines19[0:30]
df19['Departure']=DEP19[0:30]
df19['Arrival']=ARV19[0:30]
df19['Source']=origin19[0:30]
df19['Destination']=destination19[0:30]
df19['Lay_over']=Lay_over19[0:30]
df19['Price']=price19[0:30]
df19['Duration']=Dur19[0:30]
df19

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,"AirAsia, IndiGo",04:40,17:25,Kolkata,Goa,1 stop via Hyderabad,"₹ 5,217",12 h 45 m 1 stop via Hyderabad
1,Air India,09:40,20:30,Kolkata,Goa,1 stop via Mumbai,"₹ 5,876",10 h 50 m 1 stop via Mumbai
2,Spicejet,21:55,01:00,Kolkata,Goa,1 stop via Mumbai,"₹ 6,367",27 h 05 m 1 stop via Mumbai
3,Go First,17:30,23:25,Kolkata,Goa,1 stop via Mumbai,"₹ 6,403",05 h 55 m 1 stop via Mumbai
4,Spicejet,09:35,01:00,Kolkata,Goa,1 stop via Mumbai,"₹ 6,577",15 h 25 m 1 stop via Mumbai
5,"AirAsia, IndiGo",04:40,14:00,Kolkata,Goa,1 stop via Hyderabad,"₹ 6,732",09 h 20 m 1 stop via Hyderabad
6,IndiGo,19:55,07:05,Kolkata,Goa,1 stop via Hyderabad,"₹ 6,804",11 h 10 m 1 stop via Hyderabad
7,"IndiGo, AirAsia",06:50,17:25,Kolkata,Goa,1 stop via Hyderabad,"₹ 6,937",10 h 35 m 1 stop via Hyderabad
8,IndiGo,19:50,02:00,Kolkata,Goa,1 stop via Bengaluru,"₹ 7,035",06 h 10 m 1 stop via Bengaluru
9,Go First,04:55,16:30,Kolkata,Goa,1 stop via Mumbai,"₹ 7,078",11 h 35 m 1 stop via Mumbai
10,Spicejet,09:35,17:05,Kolkata,Goa,1 stop via Mumbai,"₹ 7,103",07 h 30 m 1 stop via Mumbai
11,AirAsia,16:15,22:00,Kolkata,Goa,1 stop via Bengaluru,"₹ 7,338",05 h 45 m 1 stop via Bengaluru
12,Go First,04:55,12:45,Kolkata,Goa,1 stop via Mumbai,"₹ 7,604",07 h 50 m 1 stop via Mumbai
13,AirAsia,21:35,07:00,Kolkata,Goa,1 stop via Bengaluru,"₹ 7,968",09 h 25 m 1 stop via Bengaluru
14,Air India,15:30,00:35,Kolkata,Goa,1 stop via New Delhi,"₹ 8,301",09 h 05 m 1 stop via New Delhi
15,"AirAsia, IndiGo",16:30,23:35,Kolkata,Goa,1 stop via Hyderabad,"₹ 8,304",07 h 05 m 1 stop via Hyderabad
16,Air India,11:35,20:30,Kolkata,Goa,"3 stop via Jharsuguda,Bhubaneswar,Mumbai","₹ 8,754","08 h 55 m 3 stop via Jharsuguda,Bhubaneswar,Mu..."
17,Go First,09:30,17:10,Kolkata,Goa,1 stop via Bengaluru,"₹ 9,033",07 h 40 m 1 stop via Bengaluru
18,IndiGo,10:10,18:00,Kolkata,Goa,1 stop via Mumbai,"₹ 9,169",07 h 50 m 1 stop via Mumbai

In [56]:
df19.to_csv('flight_price019.csv',index='False')

In [57]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-IXA-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635369830253&forwardFlowRequired=true&mpo=&intl=false'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name20=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines20=[]
for i in name20:
    Airlines20.append(i.get_text())
    
print(len(Airlines20))  

dep_time20=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep20, arr20 =dep_time20[::2], dep_time20[1::2]
DEP20=[]
for i in dep20:
    DEP20.append(i.get_text())
    ARV20=[]
for i in arr20:
    ARV20.append( i.get_text())
print(len(DEP20),len(ARV20))

layover20=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over20=[]
for l in layover20:
    Lay_over20.append(l.get_text())

dep_place20=soup.find_all('p', class_='darkText')
dep_place20, arr_place20 =dep_place20[::2], dep_place20[1::2]
origin20=[]
for i in dep_place20:
    origin20.append(i.get_text())
    destination20=[]
for i in arr_place20:
    destination20.append(i.get_text())
print(len(origin20),len(destination20))

price20=[]
pri20=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri20:
    price20.append(i.get_text())
    print(len(price20))


dur20=soup.find_all('div',class_="stop-info flexOne")
Dur20=[]
for i in dur20:
    soup.find_all('p')
    Dur20.append(i.get_text())
    print(len(Dur20))

14
14 14
14 14
1
2
3
4
5
6
7
8
9
10
11
12
13
14
1
2
3
4
5
6
7
8
9
10
11
12
13
14

In [58]:
df20=pd.DataFrame()
df20['Airline_name']= Airlines20[0:30]
df20['Departure']=DEP20[0:30]
df20['Arrival']=ARV20[0:30]
df20['Source']=origin20[0:30]
df20['Destination']=destination20[0:30]
df20['Lay_over']=Lay_over20[0:30]
df20['Price']=price20[0:30]
df20['Duration']=Dur20[0:30]
df20

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,IndiGo,14:20,16:50,New Delhi,Agartala,Non stop,"₹ 3,990",02 h 30 m Non stop
1,Air India,12:10,19:10,New Delhi,Agartala,1 stop via Kolkata,"₹ 4,213",07 h 1 stop via Kolkata
2,Air India,20:15,10:50,New Delhi,Agartala,1 stop via Kolkata,"₹ 4,213",14 h 35 m 1 stop via Kolkata
3,Air India,05:25,08:10,New Delhi,Agartala,Non stop,"₹ 4,520",02 h 45 m Non stop
4,Air India,05:15,19:10,New Delhi,Agartala,"2 stop via Surat,Kolkata","₹ 4,713","13 h 55 m 2 stop via Surat,Kolkata"
5,IndiGo,03:00,08:05,New Delhi,Agartala,1 stop via Kolkata,"₹ 5,208",05 h 05 m 1 stop via Kolkata
6,IndiGo,05:55,10:30,New Delhi,Agartala,1 stop via Kolkata,"₹ 5,208",04 h 35 m 1 stop via Kolkata
7,IndiGo,10:00,14:55,New Delhi,Agartala,1 stop via Kolkata,"₹ 5,208",04 h 55 m 1 stop via Kolkata
8,IndiGo,08:40,14:55,New Delhi,Agartala,1 stop via Kolkata,"₹ 5,208",06 h 15 m 1 stop via Kolkata
9,IndiGo,07:15,14:55,New Delhi,Agartala,1 stop via Kolkata,"₹ 5,208",07 h 40 m 1 stop via Kolkata
10,IndiGo,22:30,08:05,New Delhi,Agartala,1 stop via Kolkata,"₹ 5,208",09 h 35 m 1 stop via Kolkata
11,IndiGo,07:10,12:35,New Delhi,Agartala,1 stop via Guwahati,"₹ 5,289",05 h 25 m 1 stop via Guwahati
12,IndiGo,07:15,12:05,New Delhi,Agartala,1 stop via Kolkata,"₹ 5,308",04 h 50 m 1 stop via Kolkata
13,IndiGo,07:50,12:35,New Delhi,Agartala,1 stop via Guwahati,"₹ 5,489",04 h 45 m 1 stop via Guwahati

In [59]:
df20.to_csv('flight_price020.csv',index='False')

In [64]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-MLE-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635370100335&forwardFlowRequired=true&mpo=&intl=true'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name21=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines21=[]
for i in name21:
    Airlines21.append(i.get_text())
    
print(len(Airlines21))  

dep_time21=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep21, arr21 =dep_time21[::2], dep_time21[1::2]
DEP21=[]
for i in dep21:
    DEP21.append(i.get_text())
    ARV21=[]
for i in arr21:
    ARV21.append( i.get_text())
print(len(DEP21),len(ARV21))

layover21=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over21=[]
for l in layover21:
    Lay_over21.append(l.get_text())

dep_place21=soup.find_all('p', class_='darkText')
dep_place21, arr_place21 =dep_place21[::2], dep_place21[1::2]
origin21=[]
for i in dep_place21:
    origin21.append(i.get_text())
    destination21=[]
for i in arr_place21:
    destination21.append(i.get_text())
print(len(origin21),len(destination21))

price21=[]
pri21=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri21:
    price21.append(i.get_text())
    print(len(price21))


dur21=soup.find_all('div',class_="stop-info flexOne")
Dur21=[]
for i in dur21:
    soup.find_all('p')
    Dur21.append(i.get_text())
    print(len(Dur21))

17
30 30
30 30
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30

In [65]:
df21=pd.DataFrame()
df21['Airline_name']= Airlines21[0:17]
df21['Departure']=DEP21[0:17]
df21['Arrival']=ARV21[0:17]
df21['Source']=origin21[0:17]
df21['Destination']=destination21[0:17]
df21['Lay_over']=Lay_over21[0:17]
df21['Price']=price21[0:17]
df21['Duration']=Dur21[0:17]
df21

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,Air India,06:40,11:55,New Delhi,Male,1 stop via Mumbai,"₹ 8,673",05 h 45 m 1 stop via Mumbai
1,Go First,13:15,16:45,New Delhi,Male,Non stop,"₹ 15,006",04 h Non stop
2,IndiGo,04:45,08:30,New Delhi,Male,Non stop,"₹ 15,136",04 h 15 m Non stop
3,Air India,09:45,17:30,New Delhi,Male,"2 stop via Bengaluru,Thiruvananthapuram","₹ 9,114","08 h 15 m 2 stop via Bengaluru,Thiruvananthapuram"
4,Go First,06:10,17:30,New Delhi,Male,"2 stop via Bengaluru,Thiruvananthapuram","₹ 12,433","11 h 50 m 2 stop via Bengaluru,Thiruvananthapuram"
5,IndiGo,22:30,13:10,New Delhi,Male,1 stop via Mumbai,"₹ 14,149",15 h 10 m 1 stop via Mumbai
6,Go First,21:00,13:10,New Delhi,Male,1 stop via Mumbai,"₹ 14,355",16 h 40 m 1 stop via Mumbai
7,Go First,19:40,13:10,New Delhi,Male,1 stop via Mumbai,"₹ 15,033",18 h 1 stop via Mumbai
8,Vistara,18:20,11:05,New Delhi,Male,1 stop via Bengaluru,"₹ 16,265",17 h 15 m 1 stop via Bengaluru
9,IndiGo,07:20,11:05,New Delhi,Male,1 stop via Bengaluru,"₹ 16,526",28 h 15 m 1 stop via Bengaluru
10,Srilankan Airlines,19:30,14:40,New Delhi,Male,1 stop via Kochi,"₹ 16,940",19 h 40 m 1 stop via Kochi
11,IndiGo,20:30,15:30,New Delhi,Male,1 stop via Chennai,"₹ 17,931",19 h 30 m 1 stop via Chennai
12,IndiGo,17:30,15:30,New Delhi,Male,1 stop via Chennai,"₹ 17,990",22 h 30 m 1 stop via Chennai
13,IndiGo,06:05,15:40,New Delhi,Male,1 stop via Bengaluru,"₹ 20,008",10 h 05 m 1 stop via Bengaluru
14,flydubai,02:00,13:10,New Delhi,Male,1 stop via Mumbai,"₹ 47,169",11 h 40 m 1 stop via Mumbai
15,Emirates,10:20,16:55,New Delhi,Male,1 stop via Mumbai,"₹ 57,786",07 h 05 m 1 stop via Mumbai
16,"Spicejet, Emirates",09:30,16:55,New Delhi,Male,1 stop via Mumbai,"₹ 97,489",07 h 55 m 1 stop via Mumbai

In [66]:
df21.to_csv('flight_price021.csv',index='False')

In [67]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-JFK-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635370326129&forwardFlowRequired=true&mpo=&intl=true'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name22=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines22=[]
for i in name22:
    Airlines22.append(i.get_text())
    
print(len(Airlines22))  

dep_time22=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep22, arr22 =dep_time22[::2], dep_time22[1::2]
DEP22=[]
for i in dep22:
    DEP22.append(i.get_text())
    ARV22=[]
for i in arr22:
    ARV22.append( i.get_text())
print(len(DEP22),len(ARV22))

layover22=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over22=[]
for l in layover22:
    Lay_over22.append(l.get_text())

dep_place22=soup.find_all('p', class_='darkText')
dep_place22, arr_place22 =dep_place22[::2], dep_place22[1::2]
origin22=[]
for i in dep_place22:
    origin22.append(i.get_text())
    destination22=[]
for i in arr_place22:
    destination22.append(i.get_text())
print(len(origin22),len(destination22))

price22=[]
pri22=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri22:
    price22.append(i.get_text())
    print(len(price22))


dur22=soup.find_all('div',class_="stop-info flexOne")
Dur22=[]
for i in dur22:
    soup.find_all('p')
    Dur22.append(i.get_text())
    print(len(Dur22))

21
22 22
22 22
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22

In [69]:
df22=pd.DataFrame()
df22['Airline_name']= Airlines22[0:21]
df22['Departure']=DEP22[0:21]
df22['Arrival']=ARV22[0:21]
df22['Source']=origin22[0:21]
df22['Destination']=destination22[0:21]
df22['Lay_over']=Lay_over22[0:21]
df22['Price']=price22[0:21]
df22['Duration']=Dur22[0:21]
df22

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,Emirates,16:15,08:15,New Delhi,New York,1 stop via Dubai,"₹ 48,196",26 h 30 m 1 stop via Dubai
1,American Airlines,00:55,06:20,New Delhi,New York,Non stop,"₹ 54,544",15 h 55 m Non stop
2,United Airlines,23:45,04:25,New Delhi,Newark,Non stop,"₹ 62,112",15 h 10 m Non stop
3,Air India,02:25,07:15,New Delhi,Newark,Non stop,"₹ 64,702",15 h 20 m Non stop
4,Emirates,10:35,08:15,New Delhi,New York,1 stop via Dubai,"₹ 48,196",32 h 10 m 1 stop via Dubai
5,Emirates,21:25,08:15,New Delhi,New York,1 stop via Dubai,"₹ 53,341",21 h 20 m 1 stop via Dubai
6,Emirates,04:10,21:20,New Delhi,Newark,"2 stop via Dubai,Athens","₹ 60,707","27 h 40 m 2 stop via Dubai,Athens"
7,American Airlines,03:20,12:55,New Delhi,New York,1 stop via London - Heathrow Apt,"₹ 62,619",20 h 05 m 1 stop via London - Heathrow Apt
8,Emirates,04:10,14:30,New Delhi,New York,1 stop via Dubai,"₹ 62,679",20 h 50 m 1 stop via Dubai
9,Qatar Airways,21:30,14:30,New Delhi,New York,1 stop via Doha,"₹ 64,294",27 h 30 m 1 stop via Doha
10,American Airlines,00:55,16:49,New Delhi,Westchester County,"2 stop via New York,Washington-Reagan Apt","₹ 68,442","26 h 24 m 2 stop via New York,Washington-Reaga..."
11,United Airlines,01:55,11:10,New Delhi,New York-LaGuardia Apt,1 stop via Chicago,"₹ 68,833",19 h 45 m 1 stop via Chicago
12,Qatar Airways,03:40,14:30,New Delhi,New York,1 stop via Doha,"₹ 72,741",21 h 20 m 1 stop via Doha
13,"Air India, JetBlue Airways",21:30,07:55,New Delhi,New York,1 stop via Doha,"₹ 75,083",20 h 55 m 1 stop via Doha
14,Virgin Atlantic,02:30,16:29,New Delhi,New York,1 stop via Chicago,"₹ 79,460",24 h 29 m 1 stop via Chicago
15,American Airlines,03:55,15:45,New Delhi,New York,1 stop via London - Heathrow Apt,"₹ 80,007",22 h 20 m 1 stop via London - Heathrow Apt
16,KLM Royal Dutch,03:20,12:10,New Delhi,New York,1 stop via London - Heathrow Apt,"₹ 88,233",19 h 20 m 1 stop via London - Heathrow Apt
17,United Airlines,03:20,13:10,New Delhi,New York,1 stop via Amsterdam,"₹ 88,468",20 h 20 m 1 stop via Amsterdam
18,Delta Air Lines,01:55,10:20,New Delhi,Newark,1 stop via Chicago,"₹ 89,455",18 h 55 m 1 stop via Chicago
19,Ethiopian Airlines,03:55,12:25,New Delhi,New York,1 stop via London - Heathrow Apt,"₹ 1,06,014",19 h 1 stop via London - Heathrow Apt
20,All Nippon Airways,00:30,19:15,New Delhi,New York,"2 stop via Addis Ababa,Lome","₹ 1,09,050","29 h 15 m 2 stop via Addis Ababa,Lome"

In [70]:
df22.to_csv('flight_price022.csv',index='False')

In [71]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=CCU-JFK-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635370440133&forwardFlowRequired=true&mpo=&intl=true'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name23=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines23=[]
for i in name23:
    Airlines23.append(i.get_text())
    
print(len(Airlines23))  

dep_time23=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep23, arr23 =dep_time23[::2], dep_time23[1::2]
DEP23=[]
for i in dep23:
    DEP23.append(i.get_text())
    ARV23=[]
for i in arr23:
    ARV23.append( i.get_text())
print(len(DEP23),len(ARV23))

layover23=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over23=[]
for l in layover23:
    Lay_over23.append(l.get_text())

dep_place23=soup.find_all('p', class_='darkText')
dep_place23, arr_place23 =dep_place23[::2], dep_place23[1::2]
origin23=[]
for i in dep_place23:
    origin23.append(i.get_text())
    destination23=[]
for i in arr_place23:
    destination23.append(i.get_text())
print(len(origin23),len(destination23))

price23=[]
pri23=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri23:
    price23.append(i.get_text())
    print(len(price23))


dur23=soup.find_all('div',class_="stop-info flexOne")
Dur23=[]
for i in dur23:
    soup.find_all('p')
    Dur23.append(i.get_text())
    print(len(Dur23))

11
18 18
18 18
1
2
3
4
5
6
7
8
9
10
11
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18

In [73]:
df23=pd.DataFrame()
df23['Airline_name']= Airlines23[0:11]
df23['Departure']=DEP23[0:11]
df23['Arrival']=ARV23[0:11]
df23['Source']=origin23[0:11]
df23['Destination']=destination23[0:11]
df23['Lay_over']=Lay_over23[0:11]
df23['Price']=price23[0:11]
df23['Duration']=Dur23[0:11]
df23

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,Emirates,08:55,08:15,Kolkata,New York,1 stop via Dubai,"₹ 51,561",33 h 50 m 1 stop via Dubai
1,Air India,20:30,07:15,Kolkata,Newark,1 stop via New Delhi,"₹ 66,383",21 h 15 m 1 stop via New Delhi
2,"Vistara, American Airlines",15:30,07:15,Kolkata,Newark,1 stop via New Delhi,"₹ 68,589",26 h 15 m 1 stop via New Delhi
3,"Vistara, Emirates",20:20,06:20,Kolkata,New York,1 stop via New Delhi,"₹ 65,489",20 h 30 m 1 stop via New Delhi
4,Air India,20:35,21:20,Kolkata,Newark,"3 stop via Mumbai,Dubai,Athens","₹ 66,383","59 h 15 m 3 stop via Mumbai,Dubai,Athens"
5,"Vistara, American Airlines",17:35,21:20,Kolkata,Newark,"3 stop via Mumbai,Dubai,Athens","₹ 68,589","62 h 15 m 3 stop via Mumbai,Dubai,Athens"
6,"Vistara, United Airlines",10:25,07:15,Kolkata,Newark,1 stop via New Delhi,"₹ 68,999",31 h 20 m 1 stop via New Delhi
7,"Vistara, Emirates",15:20,06:20,Kolkata,New York,1 stop via New Delhi,"₹ 70,634",25 h 30 m 1 stop via New Delhi
8,United Airlines,10:15,06:20,Kolkata,New York,1 stop via New Delhi,"₹ 1,10,023",30 h 35 m 1 stop via New Delhi
9,"Vistara, United Airlines",07:10,06:20,Kolkata,New York,1 stop via New Delhi,"₹ 1,10,159",33 h 40 m 1 stop via New Delhi
10,United Airlines,15:20,04:25,Kolkata,Newark,1 stop via New Delhi,"₹ 1,14,195",23 h 35 m 1 stop via New Delhi

In [74]:
df23.to_csv('flight_price023.csv',index='False')

In [75]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=MAA-NYC-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635370748917&forwardFlowRequired=true&mpo=&intl=true'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name24=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines24=[]
for i in name24:
    Airlines24.append(i.get_text())
    
print(len(Airlines24))  

dep_time24=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep24, arr24 =dep_time24[::2], dep_time24[1::2]
DEP24=[]
for i in dep24:
    DEP24.append(i.get_text())
    ARV24=[]
for i in arr24:
    ARV24.append( i.get_text())
print(len(DEP24),len(ARV24))

layover24=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over24=[]
for l in layover24:
    Lay_over24.append(l.get_text())

dep_place24=soup.find_all('p', class_='darkText')
dep_place24, arr_place24 =dep_place24[::2], dep_place24[1::2]
origin24=[]
for i in dep_place24:
    origin24.append(i.get_text())
    destination24=[]
for i in arr_place24:
    destination24.append(i.get_text())
print(len(origin24),len(destination24))

price24=[]
pri24=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri24:
    price24.append(i.get_text())
    print(len(price24))


dur24=soup.find_all('div',class_="stop-info flexOne")
Dur24=[]
for i in dur24:
    soup.find_all('p')
    Dur24.append(i.get_text())
    print(len(Dur24))

14
18 18
18 18
1
2
3
4
5
6
7
8
9
10
11
12
13
14
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18

In [77]:
df24=pd.DataFrame()
df24['Airline_name']= Airlines24[0:14]
df24['Departure']=DEP24[0:14]
df24['Arrival']=ARV24[0:14]
df24['Source']=origin24[0:14]
df24['Destination']=destination24[0:14]
df24['Lay_over']=Lay_over24[0:14]
df24['Price']=price24[0:14]
df24['Duration']=Dur24[0:14]
df24

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,Etihad Airways,02:20,15:00,Chennai,New York,1 stop via Abu Dhabi,"₹ 43,236",23 h 10 m 1 stop via Abu Dhabi
1,"Vistara, United Airlines",17:25,04:25,Chennai,Newark,1 stop via New Delhi,"₹ 54,981",21 h 30 m 1 stop via New Delhi
2,Emirates,03:30,14:30,Chennai,New York,1 stop via Dubai,"₹ 57,932",21 h 30 m 1 stop via Dubai
3,Air India,20:20,07:15,Chennai,Newark,"2 stop via Hyderabad,New Delhi","₹ 64,815","21 h 25 m 2 stop via Hyderabad,New Delhi"
4,"Vistara, United Airlines",07:05,04:25,Chennai,Newark,1 stop via New Delhi,"₹ 54,981",31 h 50 m 1 stop via New Delhi
5,Emirates,09:45,08:15,Chennai,New York,1 stop via Dubai,"₹ 57,932",33 h 1 stop via Dubai
6,Air India,17:00,07:15,Chennai,Newark,1 stop via New Delhi,"₹ 64,815",24 h 45 m 1 stop via New Delhi
7,KLM Royal Dutch,09:55,07:15,Chennai,Newark,1 stop via New Delhi,"₹ 65,999",31 h 50 m 1 stop via New Delhi
8,Qatar Airways,06:10,07:15,Chennai,Newark,1 stop via New Delhi,"₹ 68,617",35 h 35 m 1 stop via New Delhi
9,"Vistara, Virgin Atlantic",02:20,15:50,Chennai,New York,"2 stop via Abu Dhabi,Amsterdam","₹ 85,438","24 h 2 stop via Abu Dhabi,Amsterdam"
10,"Vistara, United Airlines",03:20,14:30,Chennai,New York,1 stop via Doha,"₹ 96,141",21 h 40 m 1 stop via Doha
11,United Airlines,21:05,12:25,Chennai,New York,"2 stop via New Delhi,London - Heathrow Apt","₹ 99,235","25 h 50 m 2 stop via New Delhi,London - Heathr..."
12,United Airlines,12:30,05:25,Chennai,Newark,1 stop via Mumbai,"₹ 1,35,379",27 h 25 m 1 stop via Mumbai
13,"Vistara, British Airways, American Airlines",09:45,05:25,Chennai,Newark,1 stop via Mumbai,"₹ 1,93,850",30 h 10 m 1 stop via Mumbai

In [78]:
df24.to_csv('flight_price024.csv',index='False')

In [79]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-BOM-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635371211139&forwardFlowRequired=true&mpo=&intl=false'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name25=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines25=[]
for i in name25:
    Airlines25.append(i.get_text())
    
print(len(Airlines25))  

dep_time25=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep25, arr25 =dep_time25[::2], dep_time25[1::2]
DEP25=[]
for i in dep25:
    DEP25.append(i.get_text())
    ARV25=[]
for i in arr25:
    ARV25.append( i.get_text())
print(len(DEP25),len(ARV25))

layover25=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over25=[]
for l in layover25:
    Lay_over25.append(l.get_text())

dep_place25=soup.find_all('p', class_='darkText')
dep_place25, arr_place25 =dep_place25[::2], dep_place25[1::2]
origin25=[]
for i in dep_place25:
    origin25.append(i.get_text())
    destination25=[]
for i in arr_place25:
    destination25.append(i.get_text())
print(len(origin25),len(destination25))

price25=[]
pri25=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri25:
    price25.append(i.get_text())
    print(len(price25))


dur25=soup.find_all('div',class_="stop-info flexOne")
Dur25=[]
for i in dur25:
    soup.find_all('p')
    Dur25.append(i.get_text())
    print(len(Dur25))

39
39 39
39 39
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39

In [81]:
df25=pd.DataFrame()
df25['Airline_name']= Airlines25[0:39]
df25['Departure']=DEP25[0:39]
df25['Arrival']=ARV25[0:39]
df25['Source']=origin25[0:39]
df25['Destination']=destination25[0:39]
df25['Lay_over']=Lay_over25[0:39]
df25['Price']=price25[0:39]
df25['Duration']=Dur25[0:39]
df25

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,IndiGo,01:05,03:20,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 15 m Non stop
1,Go First,02:00,04:15,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 15 m Non stop
2,AirAsia,04:25,06:35,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 10 m Non stop
3,Go First,07:00,09:10,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 10 m Non stop
4,Go First,08:00,10:10,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 10 m Non stop
5,IndiGo,09:30,11:45,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 15 m Non stop
6,IndiGo,10:45,13:05,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 20 m Non stop
7,IndiGo,16:00,18:15,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 15 m Non stop
8,Go First,18:05,20:25,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 20 m Non stop
9,Go First,19:40,21:55,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 15 m Non stop
10,Go First,21:00,23:15,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 15 m Non stop
11,Go First,22:30,00:40,New Delhi,Mumbai,Non stop,"₹ 2,456",02 h 10 m Non stop
12,Air India,08:00,10:10,New Delhi,Mumbai,Non stop,"₹ 2,476",02 h 10 m Non stop
13,Air India,17:50,20:00,New Delhi,Mumbai,Non stop,"₹ 2,476",02 h 10 m Non stop
14,Air India,15:05,18:15,New Delhi,Mumbai,1 stop via Indore,"₹ 2,476",03 h 10 m 1 stop via Indore
15,Air India,17:50,21:35,New Delhi,Mumbai,1 stop via Aurangabad,"₹ 2,476",03 h 45 m 1 stop via Aurangabad
16,Vistara,06:00,08:00,New Delhi,Mumbai,Non stop,"₹ 2,556",02 h Non stop
17,Vistara,21:40,23:50,New Delhi,Mumbai,Non stop,"₹ 2,556",02 h 10 m Non stop
18,Spicejet,06:20,08:40,New Delhi,Mumbai,Non stop,"₹ 2,621",02 h 20 m Non stop
19,Spicejet,07:20,09:35,New Delhi,Mumbai,Non stop,"₹ 2,621",02 h 15 m Non stop
20,Spicejet,18:55,21:05,New Delhi,Mumbai,Non stop,"₹ 2,621",02 h 10 m Non stop
21,Spicejet,19:45,22:05,New Delhi,Mumbai,Non stop,"₹ 2,621",02 h 20 m Non stop
22,AirAsia,20:00,22:15,New Delhi,Mumbai,Non stop,"₹ 2,757",02 h 15 m Non stop
23,Vistara,20:40,22:50,New Delhi,Mumbai,Non stop,"₹ 2,763",02 h 10 m Non stop
24,Go First,10:30,12:50,New Delhi,Mumbai,Non stop,"₹ 2,790",02 h 20 m Non stop
25,Go First,15:00,17:15,New Delhi,Mumbai,Non stop,"₹ 2,790",02 h 15 m Non stop
26,Air India,07:00,09:05,New Delhi,Mumbai,Non stop,"₹ 2,791",02 h 05 m Non stop
27,Air India,09:00,11:15,New Delhi,Mumbai,Non stop,"₹ 2,791",02 h 15 m Non stop
28,Air India,10:40,12:50,New Delhi,Mumbai,Non stop,"₹ 2,791",02 h 10 m Non stop
29,IndiGo,12:00,14:10,New Delhi,Mumbai,Non stop,"₹ 2,791",02 h 10 m Non stop
30,Vistara,09:30,11:40,New Delhi,Mumbai,Non stop,"₹ 3,081",02 h 10 m Non stop
31,Vistara,10:20,12:35,New Delhi,Mumbai,Non stop,"₹ 3,081",02 h 15 m Non stop
32,Vistara,11:40,14:00,New Delhi,Mumbai,Non stop,"₹ 3,081",02 h 20 m Non stop
33,Vistara,12:50,15:00,New Delhi,Mumbai,Non stop,"₹ 3,081",02 h 10 m Non stop
34,Vistara,15:30,17:40,New Delhi,Mumbai,Non stop,"₹ 3,081",02 h 10 m Non stop
35,Vistara,16:55,19:05,New Delhi,Mumbai,Non stop,"₹ 3,081",02 h 10 m Non stop
36,Vistara,19:50,22:00,New Delhi,Mumbai,Non stop,"₹ 3,081",02 h 10 m Non stop
37,Air India,20:00,22:10,New Delhi,Mumbai,Non stop,"₹ 3,211",02 h 10 m Non stop
38,Spicejet,19:00,23:50,New Delhi,Mumbai,1 stop via Jaipur,"₹ 3,533",04 h 50 m 1 stop via Jaipur

In [82]:
df25.to_csv('flight_price025.csv',index='False')

In [83]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-CMB-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635371500192&forwardFlowRequired=true&mpo=&intl=true'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name26=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines26=[]
for i in name26:
    Airlines26.append(i.get_text())
    
print(len(Airlines26))  

dep_time26=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep26, arr26 =dep_time26[::2], dep_time26[1::2]
DEP26=[]
for i in dep26:
    DEP26.append(i.get_text())
    ARV26=[]
for i in arr26:
    ARV26.append( i.get_text())
print(len(DEP26),len(ARV26))

layover26=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over26=[]
for l in layover26:
    Lay_over26.append(l.get_text())

dep_place26=soup.find_all('p', class_='darkText')
dep_place26, arr_place26 =dep_place26[::2], dep_place26[1::2]
origin26=[]
for i in dep_place26:
    origin26.append(i.get_text())
    destination26=[]
for i in arr_place26:
    destination26.append(i.get_text())
print(len(origin26),len(destination26))

price26=[]
pri26=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri26:
    price26.append(i.get_text())
    print(len(price26))


dur26=soup.find_all('div',class_="stop-info flexOne")
Dur26=[]
for i in dur26:
    soup.find_all('p')
    Dur26.append(i.get_text())
    print(len(Dur26))

17
17 17
17 17
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17

In [84]:
df26=pd.DataFrame()
df26['Airline_name']= Airlines26[0:17]
df26['Departure']=DEP26[0:17]
df26['Arrival']=ARV26[0:17]
df26['Source']=origin26[0:17]
df26['Destination']=destination26[0:17]
df26['Lay_over']=Lay_over26[0:17]
df26['Price']=price26[0:17]
df26['Duration']=Dur26[0:17]
df26

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,Go First,12:15,15:45,New Delhi,Colombo,Non stop,"₹ 8,864",03 h 30 m Non stop
1,Srilankan Airlines,06:20,10:00,New Delhi,Colombo,Non stop,"₹ 14,115",03 h 40 m Non stop
2,Go First,19:35,12:05,New Delhi,Colombo,1 stop via Hyderabad,"₹ 8,864",16 h 30 m 1 stop via Hyderabad
3,Go First,06:05,14:00,New Delhi,Colombo,1 stop via Bengaluru,"₹ 11,746",07 h 55 m 1 stop via Bengaluru
4,IndiGo,20:30,12:50,New Delhi,Colombo,1 stop via Chennai,"₹ 13,149",16 h 20 m 1 stop via Chennai
5,IndiGo,17:30,12:50,New Delhi,Colombo,1 stop via Chennai,"₹ 13,149",19 h 20 m 1 stop via Chennai
6,"Vistara, Srilankan Airlines",16:55,23:25,New Delhi,Colombo,1 stop via Mumbai,"₹ 26,144",06 h 30 m 1 stop via Mumbai
7,"Vistara, Srilankan Airlines",15:30,23:25,New Delhi,Colombo,1 stop via Mumbai,"₹ 26,144",07 h 55 m 1 stop via Mumbai
8,"Vistara, Srilankan Airlines",12:50,23:25,New Delhi,Colombo,1 stop via Mumbai,"₹ 26,144",10 h 35 m 1 stop via Mumbai
9,IndiGo,23:05,12:50,New Delhi,Colombo,1 stop via Chennai,"₹ 20,885",13 h 45 m 1 stop via Chennai
10,"Vistara, Srilankan Airlines",19:55,11:20,New Delhi,Colombo,1 stop via Chennai,"₹ 21,965",15 h 25 m 1 stop via Chennai
11,"Vistara, Srilankan Airlines",20:40,11:25,New Delhi,Colombo,1 stop via Bengaluru,"₹ 24,186",14 h 45 m 1 stop via Bengaluru
12,"Vistara, Srilankan Airlines",11:40,23:25,New Delhi,Colombo,1 stop via Mumbai,"₹ 26,144",11 h 45 m 1 stop via Mumbai
13,IndiGo,18:45,12:50,New Delhi,Colombo,1 stop via Chennai,"₹ 20,885",18 h 05 m 1 stop via Chennai
14,IndiGo,16:20,12:50,New Delhi,Colombo,1 stop via Chennai,"₹ 20,885",20 h 30 m 1 stop via Chennai
15,IndiGo,12:45,12:50,New Delhi,Colombo,1 stop via Chennai,"₹ 20,885",24 h 05 m 1 stop via Chennai
16,"Air India, Srilankan Airlines",06:40,22:55,New Delhi,Colombo,"2 stop via Mumbai,Male","₹ 73,617","16 h 15 m 2 stop via Mumbai,Male"

In [85]:
df26.to_csv('flight_price026.csv',index='False')

In [86]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=BOM-CMB-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635371658396&forwardFlowRequired=true&mpo=&intl=true'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name27=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines27=[]
for i in name27:
    Airlines27.append(i.get_text())
    
print(len(Airlines27))  

dep_time27=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep27, arr27 =dep_time27[::2], dep_time27[1::2]
DEP27=[]
for i in dep27:
    DEP27.append(i.get_text())
    ARV27=[]
for i in arr27:
    ARV27.append( i.get_text())
print(len(DEP27),len(ARV27))

layover27=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over27=[]
for l in layover27:
    Lay_over27.append(l.get_text())

dep_place27=soup.find_all('p', class_='darkText')
dep_place27, arr_place27 =dep_place27[::2], dep_place27[1::2]
origin27=[]
for i in dep_place27:
    origin27.append(i.get_text())
    destination27=[]
for i in arr_place27:
    destination27.append(i.get_text())
print(len(origin27),len(destination27))

price27=[]
pri27=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri27:
    price27.append(i.get_text())
    print(len(price27))


dur27=soup.find_all('div',class_="stop-info flexOne")
Dur27=[]
for i in dur27:
    soup.find_all('p')
    Dur27.append(i.get_text())
    print(len(Dur27))

14
14 14
14 14
1
2
3
4
5
6
7
8
9
10
11
12
13
14
1
2
3
4
5
6
7
8
9
10
11
12
13
14

In [88]:
df27=pd.DataFrame()
df27['Airline_name']= Airlines27[0:14]
df27['Departure']=DEP27[0:14]
df27['Arrival']=ARV27[0:14]
df27['Source']=origin27[0:14]
df27['Destination']=destination27[0:14]
df27['Lay_over']=Lay_over27[0:14]
df27['Price']=price27[0:14]
df27['Duration']=Dur27[0:14]
df27

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,Srilankan Airlines,21:00,23:25,Mumbai,Colombo,Non stop,"₹ 14,305",02 h 25 m Non stop
1,Go First,05:50,12:10,Mumbai,Colombo,1 stop via Chennai,"₹ 6,699",06 h 20 m 1 stop via Chennai
2,Go First,06:05,14:00,Mumbai,Colombo,1 stop via Bengaluru,"₹ 11,323",07 h 55 m 1 stop via Bengaluru
3,Go First,06:00,15:45,Mumbai,Colombo,1 stop via New Delhi,"₹ 12,681",09 h 45 m 1 stop via New Delhi
4,IndiGo,07:15,12:50,Mumbai,Colombo,1 stop via Chennai,"₹ 14,982",05 h 35 m 1 stop via Chennai
5,IndiGo,04:35,12:50,Mumbai,Colombo,1 stop via Chennai,"₹ 14,982",08 h 15 m 1 stop via Chennai
6,Go First,22:50,14:00,Mumbai,Colombo,1 stop via Bengaluru,"₹ 11,323",15 h 10 m 1 stop via Bengaluru
7,Go First,21:00,14:00,Mumbai,Colombo,1 stop via Bengaluru,"₹ 11,323",17 h 1 stop via Bengaluru
8,Go First,23:45,15:45,Mumbai,Colombo,1 stop via New Delhi,"₹ 12,074",16 h 1 stop via New Delhi
9,Go First,21:15,15:45,Mumbai,Colombo,1 stop via New Delhi,"₹ 12,074",18 h 30 m 1 stop via New Delhi
10,IndiGo,23:05,12:50,Mumbai,Colombo,1 stop via Chennai,"₹ 14,982",13 h 45 m 1 stop via Chennai
11,Go First,22:40,15:45,Mumbai,Colombo,1 stop via New Delhi,"₹ 12,074",17 h 05 m 1 stop via New Delhi
12,"Vistara, Srilankan Airlines",06:20,12:10,Mumbai,Colombo,1 stop via Hyderabad,"₹ 19,682",05 h 50 m 1 stop via Hyderabad
13,"Air India, Emirates",09:35,18:20,Mumbai,Colombo,1 stop via Male,"₹ 1,71,677",08 h 45 m 1 stop via Male

In [89]:
df27.to_csv('flight_price027.csv',index='False')

In [90]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=BOM-PAR-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635372001537&forwardFlowRequired=true&mpo=&intl=true'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name28=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines28=[]
for i in name28:
    Airlines28.append(i.get_text())
    
print(len(Airlines28))  

dep_time28=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep28, arr28 =dep_time28[::2], dep_time28[1::2]
DEP28=[]
for i in dep28:
    DEP28.append(i.get_text())
    ARV28=[]
for i in arr28:
    ARV28.append( i.get_text())
print(len(DEP28),len(ARV28))

layover28=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over28=[]
for l in layover28:
    Lay_over28.append(l.get_text())

dep_place28=soup.find_all('p', class_='darkText')
dep_place28, arr_place28 =dep_place28[::2], dep_place28[1::2]
origin28=[]
for i in dep_place28:
    origin28.append(i.get_text())
    destination28=[]
for i in arr_place28:
    destination28.append(i.get_text())
print(len(origin28),len(destination28))

price28=[]
pri28=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri28:
    price28.append(i.get_text())
    print(len(price28))


dur28=soup.find_all('div',class_="stop-info flexOne")
Dur28=[]
for i in dur28:
    soup.find_all('p')
    Dur28.append(i.get_text())
    print(len(Dur28))

19
19 19
19 19
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19

In [91]:
df28=pd.DataFrame()
df28['Airline_name']= Airlines28[0:23]
df28['Departure']=DEP28[0:23]
df28['Arrival']=ARV28[0:23]
df28['Source']=origin28[0:23]
df28['Destination']=destination28[0:23]
df28['Lay_over']=Lay_over28[0:23]
df28['Price']=price28[0:23]
df28['Duration']=Dur28[0:23]
df28

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,Air India,21:30,06:45,Mumbai,Paris,1 stop via New Delhi,"₹ 25,760",13 h 45 m 1 stop via New Delhi
1,Air India,19:00,06:45,Mumbai,Paris,1 stop via New Delhi,"₹ 25,760",16 h 15 m 1 stop via New Delhi
2,Turkish Airlines,06:50,14:55,Mumbai,Paris,1 stop via Istanbul,"₹ 31,887",12 h 35 m 1 stop via Istanbul
3,Qatar Airways,21:50,06:35,Mumbai,Paris,1 stop via Doha,"₹ 34,463",13 h 15 m 1 stop via Doha
4,Air India,18:00,06:45,Mumbai,Paris,1 stop via New Delhi,"₹ 25,760",17 h 15 m 1 stop via New Delhi
5,Air India,15:25,06:45,Mumbai,Paris,"2 stop via Aurangabad,New Delhi","₹ 25,760","19 h 50 m 2 stop via Aurangabad,New Delhi"
6,Air India,20:15,06:45,Mumbai,Paris,"2 stop via Hyderabad,New Delhi","₹ 34,685","15 h 2 stop via Hyderabad,New Delhi"
7,Qatar Airways,08:50,20:30,Mumbai,Paris,1 stop via Doha,"₹ 34,463",16 h 10 m 1 stop via Doha
8,Air India,16:35,06:45,Mumbai,Paris,"2 stop via Ahmedabad,New Delhi","₹ 34,685","18 h 40 m 2 stop via Ahmedabad,New Delhi"
9,Air India,16:35,06:45,Mumbai,Paris,"2 stop via Ahmedabad,New Delhi","₹ 34,685","18 h 40 m 2 stop via Ahmedabad,New Delhi"
10,Air France,02:05,07:30,Mumbai,Paris,Non stop,"₹ 42,966",09 h 55 m Non stop
11,Emirates,19:10,08:00,Mumbai,Paris,1 stop via Dubai,"₹ 36,241",17 h 20 m 1 stop via Dubai
12,Emirates,15:30,08:00,Mumbai,Paris,1 stop via Dubai,"₹ 36,241",21 h 1 stop via Dubai
13,Emirates,04:15,12:25,Mumbai,Paris,1 stop via Dubai,"₹ 48,865",12 h 40 m 1 stop via Dubai
14,Qatar Airways,04:15,13:05,Mumbai,Paris,1 stop via Doha,"₹ 51,562",13 h 20 m 1 stop via Doha
15,British Airways,02:15,22:50,Mumbai,Paris,1 stop via London - Heathrow Apt,"₹ 42,372",25 h 05 m 1 stop via London - Heathrow Apt
16,"Vistara, Finnair",22:45,18:10,Mumbai,Paris,"2 stop via New Delhi,Helsinki","₹ 46,710","23 h 55 m 2 stop via New Delhi,Helsinki"
17,Emirates,10:25,19:30,Mumbai,Paris,1 stop via Dubai,"₹ 54,766",13 h 35 m 1 stop via Dubai
18,"Virgin Atlantic, Air France",04:00,22:05,Mumbai,Paris,1 stop via London - Heathrow Apt,"₹ 51,981",22 h 35 m 1 stop via London - Heathrow Apt

In [92]:
df28.to_csv('flight_price028.csv',index='False')

In [93]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=DEL-IXE-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635372760139&forwardFlowRequired=true&mpo=&intl=false'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name29=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines29=[]
for i in name29:
    Airlines29.append(i.get_text())
    
print(len(Airlines29))  

dep_time29=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep29, arr29 =dep_time29[::2], dep_time29[1::2]
DEP29=[]
for i in dep29:
    DEP29.append(i.get_text())
    ARV29=[]
for i in arr29:
    ARV29.append( i.get_text())
print(len(DEP29),len(ARV29))

layover29=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over29=[]
for l in layover29:
    Lay_over29.append(l.get_text())

dep_place29=soup.find_all('p', class_='darkText')
dep_place29, arr_place29 =dep_place29[::2], dep_place29[1::2]
origin29=[]
for i in dep_place29:
    origin29.append(i.get_text())
    destination29=[]
for i in arr_place29:
    destination29.append(i.get_text())
print(len(origin29),len(destination29))

price29=[]
pri29=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri29:
    price29.append(i.get_text())
    print(len(price29))


dur29=soup.find_all('div',class_="stop-info flexOne")
Dur29=[]
for i in dur29:
    soup.find_all('p')
    Dur29.append(i.get_text())
    print(len(Dur29))

19
19 19
19 19
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19

In [94]:
df29=pd.DataFrame()
df29['Airline_name']= Airlines29[0:19]
df29['Departure']=DEP29[0:19]
df29['Arrival']=ARV29[0:19]
df29['Source']=origin29[0:19]
df29['Destination']=destination29[0:19]
df29['Lay_over']=Lay_over29[0:19]
df29['Price']=price29[0:19]
df29['Duration']=Dur29[0:19]
df29

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,"Spicejet, IndiGo",06:20,12:40,New Delhi,Mangalore,1 stop via Mumbai,"₹ 4,798",06 h 20 m 1 stop via Mumbai
1,"AirAsia, IndiGo",04:25,12:40,New Delhi,Mangalore,1 stop via Mumbai,"₹ 4,798",08 h 15 m 1 stop via Mumbai
2,"Go First, IndiGo",02:00,12:40,New Delhi,Mangalore,1 stop via Mumbai,"₹ 4,798",10 h 40 m 1 stop via Mumbai
3,"Vistara, IndiGo",06:00,12:40,New Delhi,Mangalore,1 stop via Mumbai,"₹ 4,898",06 h 40 m 1 stop via Mumbai
4,"Air India, IndiGo",07:00,12:40,New Delhi,Mangalore,1 stop via Mumbai,"₹ 5,133",05 h 40 m 1 stop via Mumbai
5,Go First,07:00,11:55,New Delhi,Mangalore,1 stop via Mumbai,"₹ 5,468",04 h 55 m 1 stop via Mumbai
6,Go First,22:30,11:55,New Delhi,Mangalore,1 stop via Mumbai,"₹ 5,468",13 h 25 m 1 stop via Mumbai
7,Go First,21:00,11:55,New Delhi,Mangalore,1 stop via Mumbai,"₹ 5,468",14 h 55 m 1 stop via Mumbai
8,IndiGo,13:00,21:15,New Delhi,Mangalore,1 stop via Hyderabad,"₹ 5,795",08 h 15 m 1 stop via Hyderabad
9,"AirAsia, Go First",04:25,11:55,New Delhi,Mangalore,1 stop via Mumbai,"₹ 5,982",07 h 30 m 1 stop via Mumbai
10,"IndiGo, Go First",01:05,11:55,New Delhi,Mangalore,1 stop via Mumbai,"₹ 5,982",10 h 50 m 1 stop via Mumbai
11,"Vistara, Go First",06:00,11:55,New Delhi,Mangalore,1 stop via Mumbai,"₹ 6,082",05 h 55 m 1 stop via Mumbai
12,Spicejet,22:10,07:50,New Delhi,Mangalore,1 stop via Bengaluru,"₹ 6,090",09 h 40 m 1 stop via Bengaluru
13,IndiGo,02:30,07:45,New Delhi,Mangalore,1 stop via Bengaluru,"₹ 6,141",05 h 15 m 1 stop via Bengaluru
14,IndiGo,07:20,15:55,New Delhi,Mangalore,1 stop via Bengaluru,"₹ 6,141",08 h 35 m 1 stop via Bengaluru
15,IndiGo,09:30,20:15,New Delhi,Mangalore,1 stop via Mumbai,"₹ 6,446",10 h 45 m 1 stop via Mumbai
16,IndiGo,12:00,20:15,New Delhi,Mangalore,1 stop via Mumbai,"₹ 6,781",08 h 15 m 1 stop via Mumbai
17,"Go First, IndiGo",10:30,20:15,New Delhi,Mangalore,1 stop via Mumbai,"₹ 6,877",09 h 45 m 1 stop via Mumbai
18,Air India,07:00,12:00,New Delhi,Mangalore,1 stop via Mumbai,"₹ 6,907",05 h 1 stop via Mumbai

In [95]:
df29.to_csv('flight_price029.csv',index='False')

In [96]:
import time
url='https://www.makemytrip.com/flight/search?tripType=O&itinerary=CCU-IXE-20/12/2021&paxType=A-1_C-0_I-0&cabinClass=E&sTime=1635373022435&forwardFlowRequired=true&mpo=&intl=false'
chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome("chromedriver.exe")
driver.implicitly_wait(20)
driver.get(url)
soup=BeautifulSoup(driver.page_source, 'lxml')
time.sleep(3)

driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/label[1]/div/span[1]/span/span').click()

name30=soup.find_all('span',class_='boldFont blackText airlineName')
Airlines30=[]
for i in name30:
    Airlines30.append(i.get_text())
    
print(len(Airlines30))  

dep_time30=soup.find_all('p',class_='blackText fontSize18 blackFont appendBottom2 makeFlex hrtlCenter')
dep30, arr30 =dep_time30[::2], dep_time30[1::2]
DEP30=[]
for i in dep30:
    DEP30.append(i.get_text())
    ARV30=[]
for i in arr30:
    ARV30.append( i.get_text())
print(len(DEP30),len(ARV30))

layover30=soup.find_all('p',class_='flightsLayoverInfo')
Lay_over30=[]
for l in layover30:
    Lay_over30.append(l.get_text())

dep_place30=soup.find_all('p', class_='darkText')
dep_place30, arr_place30 =dep_place30[::2], dep_place30[1::2]
origin30=[]
for i in dep_place30:
    origin30.append(i.get_text())
    destination30=[]
for i in arr_place30:
    destination30.append(i.get_text())
print(len(origin30),len(destination30))

price30=[]
pri30=soup.find_all('p',class_='blackText fontSize18 blackFont white-space-no-wrap')
for i in pri30:
    price30.append(i.get_text())
    print(len(price30))


dur30=soup.find_all('div',class_="stop-info flexOne")
Dur30=[]
for i in dur30:
    soup.find_all('p')
    Dur30.append(i.get_text())
    print(len(Dur30))

14
14 14
14 14
1
2
3
4
5
6
7
8
9
10
11
12
13
14
1
2
3
4
5
6
7
8
9
10
11
12
13
14

In [97]:
df30=pd.DataFrame()
df30['Airline_name']= Airlines30[0:14]
df30['Departure']=DEP30[0:14]
df30['Arrival']=ARV30[0:14]
df30['Source']=origin30[0:14]
df30['Destination']=destination30[0:14]
df30['Lay_over']=Lay_over30[0:14]
df30['Price']=price30[0:14]
df30['Duration']=Dur30[0:14]
df30

,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,"IndiGo, Spicejet",06:50,20:10,Kolkata,Mangalore,1 stop via Hyderabad,"₹ 5,731",13 h 20 m 1 stop via Hyderabad
1,IndiGo,09:15,15:55,Kolkata,Mangalore,1 stop via Bengaluru,"₹ 6,088",06 h 40 m 1 stop via Bengaluru
2,IndiGo,05:25,15:55,Kolkata,Mangalore,1 stop via Bengaluru,"₹ 6,088",10 h 30 m 1 stop via Bengaluru
3,IndiGo,11:35,20:50,Kolkata,Mangalore,1 stop via Bengaluru,"₹ 6,088",09 h 15 m 1 stop via Bengaluru
4,IndiGo,21:20,07:45,Kolkata,Mangalore,1 stop via Bengaluru,"₹ 6,088",10 h 25 m 1 stop via Bengaluru
5,"AirAsia, Spicejet",04:40,20:10,Kolkata,Mangalore,1 stop via Hyderabad,"₹ 6,108",15 h 30 m 1 stop via Hyderabad
6,"Air India, IndiGo",19:00,07:45,Kolkata,Mangalore,"2 stop via Hyderabad,Bengaluru","₹ 6,178","12 h 45 m 2 stop via Hyderabad,Bengaluru"
7,"AirAsia, IndiGo",04:40,11:30,Kolkata,Mangalore,1 stop via Hyderabad,"₹ 6,530",06 h 50 m 1 stop via Hyderabad
8,Spicejet,20:05,07:50,Kolkata,Mangalore,1 stop via Bengaluru,"₹ 6,665",11 h 45 m 1 stop via Bengaluru
9,Go First,04:55,11:55,Kolkata,Mangalore,1 stop via Mumbai,"₹ 7,760",07 h 1 stop via Mumbai
10,Spicejet,12:00,20:10,Kolkata,Mangalore,"2 stop via Visakhapatnam,Hyderabad","₹ 8,208","08 h 10 m 2 stop via Visakhapatnam,Hyderabad"
11,IndiGo,13:55,21:15,Kolkata,Mangalore,1 stop via Hyderabad,"₹ 9,112",07 h 20 m 1 stop via Hyderabad
12,"IndiGo, Spicejet",13:55,20:10,Kolkata,Mangalore,1 stop via Hyderabad,"₹ 9,418",06 h 15 m 1 stop via Hyderabad
13,"Vistara, IndiGo",10:15,21:15,Kolkata,Mangalore,"2 stop via New Delhi,Hyderabad","₹ 10,060","11 h 2 stop via New Delhi,Hyderabad"

In [98]:
df30.to_csv('flight_price030.csv',index='False')

In [99]:
df1=pd.read_csv('flight_price01.csv')
df2=pd.read_csv('flight_price02.csv')
df3=pd.read_csv('flight_price03.csv')
df4=pd.read_csv('flight_price04.csv')
df5=pd.read_csv('flight_price05.csv')
df6=pd.read_csv('flight_price06.csv')
df7=pd.read_csv('flight_price07.csv')
df8=pd.read_csv('flight_price08.csv')
df9=pd.read_csv('flight_price09.csv')
df10=pd.read_csv('flight_price010.csv')
df11=pd.read_csv('flight_price011.csv')
df12=pd.read_csv('flight_price012.csv')
df13=pd.read_csv('flight_price013.csv')
df14=pd.read_csv('flight_price014.csv')
df15=pd.read_csv('flight_price015.csv')
df16=pd.read_csv('flight_price016.csv')
df17=pd.read_csv('flight_price017.csv')
df18=pd.read_csv('flight_price018.csv')
df19=pd.read_csv('flight_price019.csv')
df20=pd.read_csv('flight_price020.csv')
df21=pd.read_csv('flight_price021.csv')
df22=pd.read_csv('flight_price022.csv')
df23=pd.read_csv('flight_price023.csv')
df24=pd.read_csv('flight_price024.csv')
df25=pd.read_csv('flight_price025.csv')
df26=pd.read_csv('flight_price026.csv')
df27=pd.read_csv('flight_price027.csv')
df28=pd.read_csv('flight_price028.csv')
df29=pd.read_csv('flight_price029.csv')
df30=pd.read_csv('flight_price030.csv')

In [100]:
flight_data01=pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17,df18,df19,df20,df21,df22,df23,df24,df25,df26,df27,df28,df29,df30])

In [101]:
flight_data01

,Unnamed: 0,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,0,Go First,09:10,10:45,Ahmedabad,New Delhi,Non stop,"₹ 5,060",01 h 35 m
1,1,Go First,13:25,15:00,Ahmedabad,New Delhi,Non stop,"₹ 5,060",01 h 35 m
2,2,Go First,17:30,19:05,Ahmedabad,New Delhi,Non stop,"₹ 5,060",01 h 35 m
3,3,Spicejet,06:10,11:10,Ahmedabad,New Delhi,1 stop via Jaipur,"₹ 5,060",05 h
4,4,Spicejet,06:10,11:10,Ahmedabad,New Delhi,1 stop via Jaipur,"₹ 5,060",NaN
...,...,...,...,...,...,...,...,...,...
9,9,Go First,04:55,11:55,Kolkata,Mangalore,1 stop via Mumbai,"₹ 7,760",07 h 1 stop via Mumbai
10,10,Spicejet,12:00,20:10,Kolkata,Mangalore,"2 stop via Visakhapatnam,Hyderabad","₹ 8,208","08 h 10 m 2 stop via Visakhapatnam,Hyderabad"
11,11,IndiGo,13:55,21:15,Kolkata,Mangalore,1 stop via Hyderabad,"₹ 9,112",07 h 20 m 1 stop via Hyderabad
12,12,"IndiGo, Spicejet",13:55,20:10,Kolkata,Mangalore,1 stop via Hyderabad,"₹ 9,418",06 h 15 m 1 stop via Hyderabad
13,13,"Vistara, IndiGo",10:15,21:15,Kolkata,Mangalore,"2 stop via New Delhi,Hyderabad","₹ 10,060","11 h 2 stop via New Delhi,Hyderabad"

In [102]:
flight_data01.to_csv('flight_data01.csv',index='False')

In [103]:
df=pd.read_csv('flight_price1.csv')
df1=pd.read_csv('flight_price2.csv')
df2=pd.read_csv('flight_price3.csv')
df3=pd.read_csv('flight_price4.csv')
df4=pd.read_csv('flight_price5.csv')
df5=pd.read_csv('flight_price6.csv')
df6=pd.read_csv('flight_price7.csv')
df7=pd.read_csv('flight_price8.csv')
df8=pd.read_csv('flight_price9.csv')
df9=pd.read_csv('flight_price10.csv')
df10=pd.read_csv('flight_price11.csv')
df11=pd.read_csv('flight_price12.csv')
df12=pd.read_csv('flight_price13.csv')
df13=pd.read_csv('flight_price14.csv')
df14=pd.read_csv('flight_price15.csv')
df15=pd.read_csv('flight_price16.csv')
df16=pd.read_csv('flight_price17.csv')
df17=pd.read_csv('flight_price18.csv')
df18=pd.read_csv('flight_price19.csv')
df19=pd.read_csv('flight_price20.csv')
df20=pd.read_csv('flight_price21.csv')
df21=pd.read_csv('flight_price22.csv')
df22=pd.read_csv('flight_price23.csv')

In [104]:
flight_data=pd.concat([df,df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17,df18,df19,df20,df21,df22])
flight_data

,Unnamed: 0,Airline_name,Departure,Arrival,Source,Destination,Lay_over,Price,Duration
0,0,AirAsia,04:55,11:30,New Delhi,Bengaluru,1 stop via Kolkata,"₹ 7,422",06 h 35 m
1,1,AirAsia,04:55,11:30,New Delhi,Bengaluru,1 stop via Kolkata,"₹ 7,422",NaN
2,2,AirAsia,05:20,16:35,New Delhi,Bengaluru,"2 stop via Goa,Hyderabad","₹ 7,422",NaN
3,3,AirAsia,12:40,18:20,New Delhi,Bengaluru,1 stop via Goa,"₹ 7,422",NaN
4,4,AirAsia,11:55,18:20,New Delhi,Bengaluru,1 stop via Goa,"₹ 7,422",NaN
...,...,...,...,...,...,...,...,...,...
13,13,Air India,16:20,17:55,Patna,New Delhi,Non stop,"₹ 5,202",01 h 35 m
14,14,IndiGo,16:30,18:15,Patna,New Delhi,Non stop,"₹ 5,202",01 h 45 m
15,15,Air India,19:10,20:55,Patna,New Delhi,Non stop,"₹ 5,202",01 h 45 m
16,16,IndiGo,19:40,21:25,Patna,New Delhi,Non stop,"₹ 5,202",01 h 45 m
17,17,Vistara,20:30,22:20,Patna,New Delhi,Non stop,"₹ 5,202",01 h 50 m

In [105]:
flight_data.to_csv('flight_data.csv',index='False')